<?php
/**
* Controller code for aficion autogenerated by CASE IGNITER
*/
class aficion extends CI_Controller {

	/**
	* Controller action CREATE for controller aficion
	* autogenerated by CASE IGNITER
	*/
	public function create() {

		$data['body']['filter'] = isset($_REQUEST['filter']) ? $_REQUEST['filter'] : '' ;

		// $data = [];
		enmarcar($this, 'aficion/create', $data);
	}

	
	
	/**
	* Controller action CREATE POST for controller aficion
	* autogenerated by CASE IGNITER
	*/
	public function create_post() {
		
		$this->load->model('aficion_model');

		$nombre = ( isset( $_POST['nombre']) ? $_POST['nombre'] : null );

		try {
			$id = $this->aficion_model->create( $nombre );
			$this->list_id($id);
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la aficion $nombre";
			$this->load->view('aficion/create_message',$data);
		}	
	
	}
				
				
	
	/**
	* Controller action LIST for controller aficion
	* autogenerated by CASE IGNITER
	*/
	public function list() {
		$this->load->model('aficion_model');
		$filter = isset($_REQUEST['filter'])?$_REQUEST['filter']:'';
		$data['body']['aficion'] = ($filter == '' ? $this->aficion_model->get_all() : $this->aficion_model->get_filtered( $filter ) );
		$data['body']['filter'] = $filter ;
		enmarcar($this, 'aficion/list', $data);
	}

	/**
	* Controller private function LIST_ID for controller aficion
	* autogenerated by CASE IGNITER
	*/
	private function list_id($id) {
		$this->load->model('aficion_model');
		$data['body']['aficion'] = [ $this->aficion_model->get_by_id($id) ];
		enmarcar($this, 'aficion/list', $data);
	}


	
	/**
	* Controller action DELETE for controller aficion
	* autogenerated by CASE IGNITER
	*/
	public function delete() {
		$this -> load -> model ('aficion_model');
		try {
			$id = $_POST['id'];
			$filter = isset ($_REQUEST['filter'] ) ? $_REQUEST['filter'] : '';

			$this -> aficion_model -> delete( $id );
			redirect(base_url().'aficion/list?filter='.$filter);
		}
		catch (Exception $e ) {
			enmarcar($this, 'aficion/deleteERROR');
		}
	}	
	
	
	/**
	* Controller action UPDATE for controller aficion
	* autogenerated by CASE IGNITER
	*/
	public function update() {

		$data['body']['filter'] = isset($_REQUEST['filter']) ? $_REQUEST['filter'] : '' ;


		$this -> load -> model ('aficion_model');
		$id = $_POST['id'];
		$data['body']['aficion'] = $this -> aficion_model -> get_by_id($id);
		
		enmarcar($this, 'aficion/update', $data);
	}	
	
	/**
	* Controller action UPDATE POST for controller aficion
	* autogenerated by CASE IGNITER
	*/
	public function update_post() {
	
		$this->load->model('aficion_model');
			
		$id = ( isset( $_POST['id']) ? $_POST['id'] : null );
		$nombre = ( isset( $_POST['nombre']) ? $_POST['nombre'] : null );

		try {
			$this->aficion_model->update( $id, $nombre );

			$filter = isset($_POST['filter']) ? $_POST['filter'] : '' ;
			redirect( base_url() . 'aficion/list?filter='.$filter );
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la aficion $nombre";
			$this->load->view('aficion/create_message',$data);
		}	
	
	}
			
			}
?>