<?php
/**
* Controller code for aficion autogenerated by CASE IGNITER
*/
class aficion extends CI_Controller {

	/**
	* Controller action CREATE for controller aficion
	* autogenerated by CASE IGNITER
	*/
	public function create() {

		$this->load->model('persona_model');
		$data['body']['persona'] = $this->persona_model->get_all();

		enmarcar($this, 'aficion/create', $data);
	}

	
	
	/**
	* Controller action CREATE POST for controller aficion
	* autogenerated by CASE IGNITER
	*/
	public function create_post() {
		
		$this->load->model('aficion_model');

		$nombre = ( isset( $_POST['nombre']) ? $_POST['nombre'] : null );
		$tiene_pa = ( isset( $_POST['tiene_pa']) ? $_POST['tiene_pa'] : [] );

		try {
			$this->aficion_model->create( $nombre, $tiene_pa );
			$data['status'] = 'ok';
			$data['message'] = "Aficion $nombre creado/a correctamente";
			$this->load->view('aficion/create_message',$data);
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = 'Error al crear el/la aficion $nombre';
			$this->load->view('aficion/create_message',$data);
		}	
	
	}
				
					public function list() {
		$this->load->model('aficion_model');
		$filter = isset($_POST['filter'])?$_POST['filter']:'';
		$data['body']['aficion'] = ($filter == '' ? $this->aficion_model->get_all() : $this->aficion_model->get_filtered( $filter ) );
		enmarcar($this, 'aficion/list', $data);
	}}
?>