<?php
/**
* Controller code for asignatura autogenerated by CASE IGNITER
*/
class asignatura extends CI_Controller {

	/**
	* Controller action CREATE for controller asignatura
	* autogenerated by CASE IGNITER
	*/
	public function create() {

		$this->load->model('departamento_model');
		$data['body']['departamento'] = $this->departamento_model->get_all();

		$this->load->model('imparticion_model');
		$data['body']['imparticion'] = $this->imparticion_model->get_all();

		enmarcar($this, 'asignatura/create', $data);
	}

	
	
	/**
	* Controller action CREATE POST for controller asignatura
	* autogenerated by CASE IGNITER
	*/
	public function create_post() {
		
		$this->load->model('asignatura_model');

		$nombre = ( isset( $_POST['nombre']) ? $_POST['nombre'] : null );
		$imparte = ( isset( $_POST['imparte']) ? $_POST['imparte'] : [] );
		$refierea = ( isset( $_POST['refierea']) ? $_POST['refierea'] : [] );

		try {
			$id = $this->asignatura_model->create( $nombre, $imparte, $refierea );
			$this->list_id($id);
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la asignatura $nombre";
			$this->load->view('asignatura/create_message',$data);
		}	
	
	}
				
				
	
	/**
	* Controller action LIST for controller asignatura
	* autogenerated by CASE IGNITER
	*/
	public function list() {
		$this->load->model('asignatura_model');
		$filter = isset($_POST['filter'])?$_POST['filter']:'';
		$data['body']['asignatura'] = ($filter == '' ? $this->asignatura_model->get_all() : $this->asignatura_model->get_filtered( $filter ) );
		enmarcar($this, 'asignatura/list', $data);
	}

	/**
	* Controller private function LIST_ID for controller asignatura
	* autogenerated by CASE IGNITER
	*/
	private function list_id($id) {
		$this->load->model('asignatura_model');
		$data['body']['asignatura'] = [ $this->asignatura_model->get_by_id($id) ];
		enmarcar($this, 'asignatura/list', $data);
	}


	
	/**
	* Controller action DELETE for controller asignatura
	* autogenerated by CASE IGNITER
	*/
	public function delete() {
		$this -> load -> model ('asignatura_model');
		try {
			$id = $_POST['id'];
			$this -> asignatura_model -> delete( $id );
			redirect(base_url().'asignatura/list');
		}
		catch (Exception $e ) {
			enmarcar($this, 'asignatura/deleteERROR');
		}
	}	
	
	
	/**
	* Controller action UPDATE for controller asignatura
	* autogenerated by CASE IGNITER
	*/
	public function update() {	
	
		$this->load->model('departamento_model');
		$data['body']['departamento'] = $this->departamento_model->get_all();	
	
		$this->load->model('imparticion_model');
		$data['body']['imparticion'] = $this->imparticion_model->get_all();

		$this -> load -> model ('asignatura_model');
		$id = $_POST['id'];
		$data['body']['asignatura'] = $this -> asignatura_model -> get_by_id($id);
		
		enmarcar($this, 'asignatura/update', $data);
	}	
	
	/**
	* Controller action UPDATE POST for controller asignatura
	* autogenerated by CASE IGNITER
	*/
	public function update_post() {
	
		$this->load->model('asignatura_model');
			
		$id = ( isset( $_POST['id']) ? $_POST['id'] : null );
		$nombre = ( isset( $_POST['nombre']) ? $_POST['nombre'] : null );
		$imparte = ( isset( $_POST['imparte']) ? $_POST['imparte'] : [] );
		$refierea = ( isset( $_POST['refierea']) ? $_POST['refierea'] : [] );

		try {
			$this->asignatura_model->update( $id, $nombre, $imparte, $refierea );


			redirect( base_url() . 'asignatura/list' );
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la asignatura $nombre";
			$this->load->view('asignatura/create_message',$data);
		}	
	
	}
			
			}
?>