<?php
/**
* Controller code for categoria autogenerated by CASE IGNITER
*/
class categoria extends CI_Controller {

	/**
	* Controller action CREATE for controller categoria
	* autogenerated by CASE IGNITER
	*/
	public function create() {

		$this->load->model('preguntacerrada_model');
		$data['body']['preguntacerrada'] = $this->preguntacerrada_model->get_all();

		$this->load->model('preguntaabierta_model');
		$data['body']['preguntaabierta'] = $this->preguntaabierta_model->get_all();

		enmarcar($this, 'categoria/create', $data);
	}

	
	
	/**
	* Controller action CREATE POST for controller categoria
	* autogenerated by CASE IGNITER
	*/
	public function create_post() {
		
		$this->load->model('categoria_model');

		$nombre = ( isset( $_POST['nombre']) ? $_POST['nombre'] : null );
		$contienepc = ( isset( $_POST['contienepc']) ? $_POST['contienepc'] : [] );
		$contienepa = ( isset( $_POST['contienepa']) ? $_POST['contienepa'] : [] );

		try {
			$id = $this->categoria_model->create( $nombre, $contienepc, $contienepa );
			$this->list_id($id);
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la categoria $nombre";
			$this->load->view('categoria/create_message',$data);
		}	
	
	}
				
				
	
	/**
	* Controller action LIST for controller categoria
	* autogenerated by CASE IGNITER
	*/
	public function list() {
		$this->load->model('categoria_model');
		$filter = isset($_POST['filter'])?$_POST['filter']:'';
		$data['body']['categoria'] = ($filter == '' ? $this->categoria_model->get_all() : $this->categoria_model->get_filtered( $filter ) );
		enmarcar($this, 'categoria/list', $data);
	}

	/**
	* Controller private function LIST_ID for controller categoria
	* autogenerated by CASE IGNITER
	*/
	private function list_id($id) {
		$this->load->model('categoria_model');
		$data['body']['categoria'] = [ $this->categoria_model->get_by_id($id) ];
		enmarcar($this, 'categoria/list', $data);
	}


	
	/**
	* Controller action DELETE for controller categoria
	* autogenerated by CASE IGNITER
	*/
	public function delete() {
		$this -> load -> model ('categoria_model');
		try {
			$id = $_POST['id'];
			$this -> categoria_model -> delete( $id );
			redirect(base_url().'categoria/list');
		}
		catch (Exception $e ) {
			enmarcar($this, 'categoria/deleteERROR');
		}
	}	
	
	
	/**
	* Controller action UPDATE for controller categoria
	* autogenerated by CASE IGNITER
	*/
	public function update() {	
	
		$this->load->model('preguntacerrada_model');
		$data['body']['preguntacerrada'] = $this->preguntacerrada_model->get_all();	
	
		$this->load->model('preguntaabierta_model');
		$data['body']['preguntaabierta'] = $this->preguntaabierta_model->get_all();

		$this -> load -> model ('categoria_model');
		$id = $_POST['id'];
		$data['body']['categoria'] = $this -> categoria_model -> get_by_id($id);
		
		enmarcar($this, 'categoria/update', $data);
	}	
	
	/**
	* Controller action UPDATE POST for controller categoria
	* autogenerated by CASE IGNITER
	*/
	public function update_post() {
	
		$this->load->model('categoria_model');
			
		$id = ( isset( $_POST['id']) ? $_POST['id'] : null );
		$nombre = ( isset( $_POST['nombre']) ? $_POST['nombre'] : null );
		$contienepc = ( isset( $_POST['contienepc']) ? $_POST['contienepc'] : [] );
		$contienepa = ( isset( $_POST['contienepa']) ? $_POST['contienepa'] : [] );

		try {
			$this->categoria_model->update( $id, $nombre, $contienepc, $contienepa );


			redirect( base_url() . 'categoria/list' );
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la categoria $nombre";
			$this->load->view('categoria/create_message',$data);
		}	
	
	}
			
			}
?>