<?php
/**
* Controller code for cursoacademico autogenerated by CASE IGNITER
*/
class cursoacademico extends CI_Controller {

	/**
	* Controller action CREATE for controller cursoacademico
	* autogenerated by CASE IGNITER
	*/
	public function create() {

		$this->load->model('ies_model');
		$data['body']['ies'] = $this->ies_model->get_all();

		$this->load->model('imparticion_model');
		$data['body']['imparticion'] = $this->imparticion_model->get_all();

		$this->load->model('usuario_model');
		$data['body']['usuario'] = $this->usuario_model->get_all();

		enmarcar($this, 'cursoacademico/create', $data);
	}

	
	
	/**
	* Controller action CREATE POST for controller cursoacademico
	* autogenerated by CASE IGNITER
	*/
	public function create_post() {
		
		$this->load->model('cursoacademico_model');

		$anyoini = ( isset( $_POST['anyoini']) ? $_POST['anyoini'] : null );
		$ocurre = ( isset( $_POST['ocurre']) ? $_POST['ocurre'] : [] );
		$tieneim = ( isset( $_POST['tieneim']) ? $_POST['tieneim'] : [] );
		$trabaja = ( isset( $_POST['trabaja']) ? $_POST['trabaja'] : [] );

		try {
			$id = $this->cursoacademico_model->create( $anyoini, $ocurre, $tieneim, $trabaja );
			$this->list_id($id);
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la cursoacademico $anyoini";
			$this->load->view('cursoacademico/create_message',$data);
		}	
	
	}
				
				
	
	/**
	* Controller action LIST for controller cursoacademico
	* autogenerated by CASE IGNITER
	*/
	public function list() {
		$this->load->model('cursoacademico_model');
		$filter = isset($_POST['filter'])?$_POST['filter']:'';
		$data['body']['cursoacademico'] = ($filter == '' ? $this->cursoacademico_model->get_all() : $this->cursoacademico_model->get_filtered( $filter ) );
		enmarcar($this, 'cursoacademico/list', $data);
	}

	/**
	* Controller private function LIST_ID for controller cursoacademico
	* autogenerated by CASE IGNITER
	*/
	private function list_id($id) {
		$this->load->model('cursoacademico_model');
		$data['body']['cursoacademico'] = [ $this->cursoacademico_model->get_by_id($id) ];
		enmarcar($this, 'cursoacademico/list', $data);
	}


	
	/**
	* Controller action DELETE for controller cursoacademico
	* autogenerated by CASE IGNITER
	*/
	public function delete() {
		$this -> load -> model ('cursoacademico_model');
		try {
			$id = $_POST['id'];
			$this -> cursoacademico_model -> delete( $id );
			redirect(base_url().'cursoacademico/list');
		}
		catch (Exception $e ) {
			enmarcar($this, 'cursoacademico/deleteERROR');
		}
	}	
	
	
	/**
	* Controller action UPDATE for controller cursoacademico
	* autogenerated by CASE IGNITER
	*/
	public function update() {	
	
		$this->load->model('ies_model');
		$data['body']['ies'] = $this->ies_model->get_all();	
	
		$this->load->model('imparticion_model');
		$data['body']['imparticion'] = $this->imparticion_model->get_all();	
	
		$this->load->model('usuario_model');
		$data['body']['usuario'] = $this->usuario_model->get_all();

		$this -> load -> model ('cursoacademico_model');
		$id = $_POST['id'];
		$data['body']['cursoacademico'] = $this -> cursoacademico_model -> get_by_id($id);
		
		enmarcar($this, 'cursoacademico/update', $data);
	}	
	
	/**
	* Controller action UPDATE POST for controller cursoacademico
	* autogenerated by CASE IGNITER
	*/
	public function update_post() {
	
		$this->load->model('cursoacademico_model');
			
		$id = ( isset( $_POST['id']) ? $_POST['id'] : null );
		$anyoini = ( isset( $_POST['anyoini']) ? $_POST['anyoini'] : null );
		$ocurre = ( isset( $_POST['ocurre']) ? $_POST['ocurre'] : [] );
		$tieneim = ( isset( $_POST['tieneim']) ? $_POST['tieneim'] : [] );
		$trabaja = ( isset( $_POST['trabaja']) ? $_POST['trabaja'] : [] );

		try {
			$this->cursoacademico_model->update( $id, $anyoini, $ocurre, $tieneim, $trabaja );


			redirect( base_url() . 'cursoacademico/list' );
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la cursoacademico $anyoini";
			$this->load->view('cursoacademico/create_message',$data);
		}	
	
	}
			
			}
?>