<?php
/**
* Controller code for curso autogenerated by CASE IGNITER
*/
class curso extends CI_Controller {

	/**
	* Controller action CREATE for controller curso
	* autogenerated by CASE IGNITER
	*/
	public function create() {

		$this->load->model('grupo_model');
		$data['body']['grupo'] = $this->grupo_model->get_all();

		$this->load->model('titulacion_model');
		$data['body']['titulacion'] = $this->titulacion_model->get_all();

		enmarcar($this, 'curso/create', $data);
	}

	
	
	/**
	* Controller action CREATE POST for controller curso
	* autogenerated by CASE IGNITER
	*/
	public function create_post() {
		
		$this->load->model('curso_model');

		$nivel = ( isset( $_POST['nivel']) ? $_POST['nivel'] : null );
		$pertenece = ( isset( $_POST['pertenece']) ? $_POST['pertenece'] : [] );
		$tienetit = ( isset( $_POST['tienetit']) ? $_POST['tienetit'] : [] );

		try {
			$id = $this->curso_model->create( $nivel, $pertenece, $tienetit );
			$this->list_id($id);
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la curso $nivel";
			$this->load->view('curso/create_message',$data);
		}	
	
	}
				
				
	
	/**
	* Controller action LIST for controller curso
	* autogenerated by CASE IGNITER
	*/
	public function list() {
		$this->load->model('curso_model');
		$filter = isset($_POST['filter'])?$_POST['filter']:'';
		$data['body']['curso'] = ($filter == '' ? $this->curso_model->get_all() : $this->curso_model->get_filtered( $filter ) );
		enmarcar($this, 'curso/list', $data);
	}

	/**
	* Controller private function LIST_ID for controller curso
	* autogenerated by CASE IGNITER
	*/
	private function list_id($id) {
		$this->load->model('curso_model');
		$data['body']['curso'] = [ $this->curso_model->get_by_id($id) ];
		enmarcar($this, 'curso/list', $data);
	}


	
	/**
	* Controller action DELETE for controller curso
	* autogenerated by CASE IGNITER
	*/
	public function delete() {
		$this -> load -> model ('curso_model');
		try {
			$id = $_POST['id'];
			$this -> curso_model -> delete( $id );
			redirect(base_url().'curso/list');
		}
		catch (Exception $e ) {
			enmarcar($this, 'curso/deleteERROR');
		}
	}	
	
	
	/**
	* Controller action UPDATE for controller curso
	* autogenerated by CASE IGNITER
	*/
	public function update() {	
	
		$this->load->model('grupo_model');
		$data['body']['grupo'] = $this->grupo_model->get_all();	
	
		$this->load->model('titulacion_model');
		$data['body']['titulacion'] = $this->titulacion_model->get_all();

		$this -> load -> model ('curso_model');
		$id = $_POST['id'];
		$data['body']['curso'] = $this -> curso_model -> get_by_id($id);
		
		enmarcar($this, 'curso/update', $data);
	}	
	
	/**
	* Controller action UPDATE POST for controller curso
	* autogenerated by CASE IGNITER
	*/
	public function update_post() {
	
		$this->load->model('curso_model');
			
		$id = ( isset( $_POST['id']) ? $_POST['id'] : null );
		$nivel = ( isset( $_POST['nivel']) ? $_POST['nivel'] : null );
		$pertenece = ( isset( $_POST['pertenece']) ? $_POST['pertenece'] : [] );
		$tienetit = ( isset( $_POST['tienetit']) ? $_POST['tienetit'] : [] );

		try {
			$this->curso_model->update( $id, $nivel, $pertenece, $tienetit );


			redirect( base_url() . 'curso/list' );
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la curso $nivel";
			$this->load->view('curso/create_message',$data);
		}	
	
	}
			
			}
?>