<?php
/**
* Controller code for departamento autogenerated by CASE IGNITER
*/
class departamento extends CI_Controller {

	/**
	* Controller action CREATE for controller departamento
	* autogenerated by CASE IGNITER
	*/
	public function create() {

		$this->load->model('usuario_model');
		$data['body']['usuario'] = $this->usuario_model->get_all();

		$this->load->model('asignatura_model');
		$data['body']['asignatura'] = $this->asignatura_model->get_all();

		$this->load->model('titulacion_model');
		$data['body']['titulacion'] = $this->titulacion_model->get_all();

		enmarcar($this, 'departamento/create', $data);
	}

	
	
	/**
	* Controller action CREATE POST for controller departamento
	* autogenerated by CASE IGNITER
	*/
	public function create_post() {
		
		$this->load->model('departamento_model');

		$nombre = ( isset( $_POST['nombre']) ? $_POST['nombre'] : null );
		$pertenece = ( isset( $_POST['pertenece']) ? $_POST['pertenece'] : [] );
		$imparte = ( isset( $_POST['imparte']) ? $_POST['imparte'] : [] );
		$gestiona = ( isset( $_POST['gestiona']) ? $_POST['gestiona'] : [] );

		try {
			$id = $this->departamento_model->create( $nombre, $pertenece, $imparte, $gestiona );
			$this->list_id($id);
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la departamento $nombre";
			$this->load->view('departamento/create_message',$data);
		}	
	
	}
				
				
	
	/**
	* Controller action LIST for controller departamento
	* autogenerated by CASE IGNITER
	*/
	public function list() {
		$this->load->model('departamento_model');
		$filter = isset($_POST['filter'])?$_POST['filter']:'';
		$data['body']['departamento'] = ($filter == '' ? $this->departamento_model->get_all() : $this->departamento_model->get_filtered( $filter ) );
		enmarcar($this, 'departamento/list', $data);
	}

	/**
	* Controller private function LIST_ID for controller departamento
	* autogenerated by CASE IGNITER
	*/
	private function list_id($id) {
		$this->load->model('departamento_model');
		$data['body']['departamento'] = [ $this->departamento_model->get_by_id($id) ];
		enmarcar($this, 'departamento/list', $data);
	}


	
	/**
	* Controller action DELETE for controller departamento
	* autogenerated by CASE IGNITER
	*/
	public function delete() {
		$this -> load -> model ('departamento_model');
		try {
			$id = $_POST['id'];
			$this -> departamento_model -> delete( $id );
			redirect(base_url().'departamento/list');
		}
		catch (Exception $e ) {
			enmarcar($this, 'departamento/deleteERROR');
		}
	}	
	
	
	/**
	* Controller action UPDATE for controller departamento
	* autogenerated by CASE IGNITER
	*/
	public function update() {	
	
		$this->load->model('usuario_model');
		$data['body']['usuario'] = $this->usuario_model->get_all();	
	
		$this->load->model('asignatura_model');
		$data['body']['asignatura'] = $this->asignatura_model->get_all();	
	
		$this->load->model('titulacion_model');
		$data['body']['titulacion'] = $this->titulacion_model->get_all();

		$this -> load -> model ('departamento_model');
		$id = $_POST['id'];
		$data['body']['departamento'] = $this -> departamento_model -> get_by_id($id);
		
		enmarcar($this, 'departamento/update', $data);
	}	
	
	/**
	* Controller action UPDATE POST for controller departamento
	* autogenerated by CASE IGNITER
	*/
	public function update_post() {
	
		$this->load->model('departamento_model');
			
		$id = ( isset( $_POST['id']) ? $_POST['id'] : null );
		$nombre = ( isset( $_POST['nombre']) ? $_POST['nombre'] : null );
		$pertenece = ( isset( $_POST['pertenece']) ? $_POST['pertenece'] : [] );
		$imparte = ( isset( $_POST['imparte']) ? $_POST['imparte'] : [] );
		$gestiona = ( isset( $_POST['gestiona']) ? $_POST['gestiona'] : [] );

		try {
			$this->departamento_model->update( $id, $nombre, $pertenece, $imparte, $gestiona );


			redirect( base_url() . 'departamento/list' );
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la departamento $nombre";
			$this->load->view('departamento/create_message',$data);
		}	
	
	}
			
			}
?>