<?php
/**
* Controller code for encuesta autogenerated by CASE IGNITER
*/
class encuesta extends CI_Controller {

	/**
	* Controller action CREATE for controller encuesta
	* autogenerated by CASE IGNITER
	*/
	public function create() {

		$this->load->model('usuario_model');
		$data['body']['usuario'] = $this->usuario_model->get_all();

		$this->load->model('imparticion_model');
		$data['body']['imparticion'] = $this->imparticion_model->get_all();

		$this->load->model('plantillaencuesta_model');
		$data['body']['plantillaencuesta'] = $this->plantillaencuesta_model->get_all();

		$this->load->model('respuestacerrada_model');
		$data['body']['respuestacerrada'] = $this->respuestacerrada_model->get_all();

		$this->load->model('respuestaabierta_model');
		$data['body']['respuestaabierta'] = $this->respuestaabierta_model->get_all();

		enmarcar($this, 'encuesta/create', $data);
	}

	
	
	/**
	* Controller action CREATE POST for controller encuesta
	* autogenerated by CASE IGNITER
	*/
	public function create_post() {
		
		$this->load->model('encuesta_model');

		$fecha = ( isset( $_POST['fecha']) ? $_POST['fecha'] : null );
		$realiza = ( isset( $_POST['realiza']) ? $_POST['realiza'] : [] );
		$realizada = ( isset( $_POST['realizada']) ? $_POST['realizada'] : [] );
		$acercade = ( isset( $_POST['acercade']) ? $_POST['acercade'] : [] );
		$responderc = ( isset( $_POST['responderc']) ? $_POST['responderc'] : [] );
		$respondera = ( isset( $_POST['respondera']) ? $_POST['respondera'] : [] );

		try {
			$id = $this->encuesta_model->create( $fecha, $realiza, $realizada, $acercade, $responderc, $respondera );
			$this->list_id($id);
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la encuesta $fecha";
			$this->load->view('encuesta/create_message',$data);
		}	
	
	}
				
				
	
	/**
	* Controller action LIST for controller encuesta
	* autogenerated by CASE IGNITER
	*/
	public function list() {
		$this->load->model('encuesta_model');
		$filter = isset($_POST['filter'])?$_POST['filter']:'';
		$data['body']['encuesta'] = ($filter == '' ? $this->encuesta_model->get_all() : $this->encuesta_model->get_filtered( $filter ) );
		enmarcar($this, 'encuesta/list', $data);
	}

	/**
	* Controller private function LIST_ID for controller encuesta
	* autogenerated by CASE IGNITER
	*/
	private function list_id($id) {
		$this->load->model('encuesta_model');
		$data['body']['encuesta'] = [ $this->encuesta_model->get_by_id($id) ];
		enmarcar($this, 'encuesta/list', $data);
	}


	
	/**
	* Controller action DELETE for controller encuesta
	* autogenerated by CASE IGNITER
	*/
	public function delete() {
		$this -> load -> model ('encuesta_model');
		try {
			$id = $_POST['id'];
			$this -> encuesta_model -> delete( $id );
			redirect(base_url().'encuesta/list');
		}
		catch (Exception $e ) {
			enmarcar($this, 'encuesta/deleteERROR');
		}
	}	
	
	
	/**
	* Controller action UPDATE for controller encuesta
	* autogenerated by CASE IGNITER
	*/
	public function update() {	
	
		$this->load->model('usuario_model');
		$data['body']['usuario'] = $this->usuario_model->get_all();	
	
		$this->load->model('imparticion_model');
		$data['body']['imparticion'] = $this->imparticion_model->get_all();	
	
		$this->load->model('plantillaencuesta_model');
		$data['body']['plantillaencuesta'] = $this->plantillaencuesta_model->get_all();	
	
		$this->load->model('respuestacerrada_model');
		$data['body']['respuestacerrada'] = $this->respuestacerrada_model->get_all();	
	
		$this->load->model('respuestaabierta_model');
		$data['body']['respuestaabierta'] = $this->respuestaabierta_model->get_all();

		$this -> load -> model ('encuesta_model');
		$id = $_POST['id'];
		$data['body']['encuesta'] = $this -> encuesta_model -> get_by_id($id);
		
		enmarcar($this, 'encuesta/update', $data);
	}	
	
	/**
	* Controller action UPDATE POST for controller encuesta
	* autogenerated by CASE IGNITER
	*/
	public function update_post() {
	
		$this->load->model('encuesta_model');
			
		$id = ( isset( $_POST['id']) ? $_POST['id'] : null );
		$fecha = ( isset( $_POST['fecha']) ? $_POST['fecha'] : null );
		$realiza = ( isset( $_POST['realiza']) ? $_POST['realiza'] : [] );
		$realizada = ( isset( $_POST['realizada']) ? $_POST['realizada'] : [] );
		$acercade = ( isset( $_POST['acercade']) ? $_POST['acercade'] : [] );
		$responderc = ( isset( $_POST['responderc']) ? $_POST['responderc'] : [] );
		$respondera = ( isset( $_POST['respondera']) ? $_POST['respondera'] : [] );

		try {
			$this->encuesta_model->update( $id, $fecha, $realiza, $realizada, $acercade, $responderc, $respondera );


			redirect( base_url() . 'encuesta/list' );
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la encuesta $fecha";
			$this->load->view('encuesta/create_message',$data);
		}	
	
	}
			
			}
?>