<?php
/**
* Controller code for gatito autogenerated by CASE IGNITER
*/
class gatito extends CI_Controller {	
	
	/**
	* Controller action CREATE for controller gatito
	* autogenerated by CASE IGNITER
	*/
	public function create() {
	
		
		if (session_status () == PHP_SESSION_NONE) {session_start ();}
		$rol_ok = false;
		$login_rol = (isset($_SESSION['rol']) ? $_SESSION['rol']->nombre : null );
		if ($login_rol == 'admin') {$rol_ok = true;}

		if ( !$rol_ok ) {
			show_404();
		} 
		
		$data['body']['filter'] = isset($_REQUEST['filter']) ? $_REQUEST['filter'] : '' ;	
		frame($this, 'gatito/create', $data);
	}
				
					
	
	/**
	* Controller action CREATE POST for controller gatito
	* autogenerated by CASE IGNITER
	*/
	public function create_post() {
		
		
		if (session_status () == PHP_SESSION_NONE) {session_start ();}
		$rol_ok = false;
		$login_rol = (isset($_SESSION['rol']) ? $_SESSION['rol']->nombre : null );
		if ($login_rol == 'admin') {$rol_ok = true;}

		if ( !$rol_ok ) {
			show_404();
		} 

		$this->load->model('gatito_model');

		$nombre = ( isset( $_POST['nombre']) ? $_POST['nombre'] : null );
		$fecha = ( isset( $_POST['fecha']) ? $_POST['fecha'] : null );
		$loginname = ( isset( $_POST['loginname']) ? $_POST['loginname'] : null );
		$password = ( isset( $_POST['password']) ? password_hash($_POST['password'], PASSWORD_DEFAULT) : password_hash('',PASSWORD_DEFAULT ) );
		
		$this -> load -> model('rol_model');
		$default_rol  = $this->rol_model->get_default_rol();
		if ( $default_rol == null ) {
			throw new Exception('ERROR: Default rol not defined');
		}
		$roles = [ $default_rol->id ];
		
		try {
			$id = $this->gatito_model->create( $nombre, $fecha, $loginname, $password, $roles );
			$this->list_id($id);
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la gatito $nombre";
			frame($this,'gatito/create_message',$data);
		}	
	
	}
				
				
	
	/**
	* Controller action LIST for controller gatito
	* autogenerated by CASE IGNITER
	*/
	public function list() {

		
		if (session_status () == PHP_SESSION_NONE) {session_start ();}
		$rol_ok = false;
		$login_rol = (isset($_SESSION['rol']) ? $_SESSION['rol']->nombre : null );
		if ($login_rol == 'admin') {$rol_ok = true;}

		if ( !$rol_ok ) {
			show_404();
		} 


		$this->load->model('gatito_model');
		$filter = isset($_REQUEST['filter'])?$_REQUEST['filter']:'';
		$data['body']['gatito'] = ($filter == '' ? $this->gatito_model->get_all() : $this->gatito_model->get_filtered( $filter ) );
		$data['body']['filter'] = $filter ;
		frame($this, 'gatito/list', $data);
	}

	/**
	* Controller private function LIST_ID for controller gatito
	* autogenerated by CASE IGNITER
	*/
	private function list_id($id) {
		$this->load->model('gatito_model');
		$data['body']['gatito'] = [ $this->gatito_model->get_by_id($id) ];
		frame($this, 'gatito/list', $data);
	}


	
	/**
	* Controller action DELETE for controller gatito
	* autogenerated by CASE IGNITER
	*/
	public function delete() {

		
		if (session_status () == PHP_SESSION_NONE) {session_start ();}
		$rol_ok = false;
		$login_rol = (isset($_SESSION['rol']) ? $_SESSION['rol']->nombre : null );
		if ($login_rol == 'admin') {$rol_ok = true;}

		if ( !$rol_ok ) {
			show_404();
		} 


		$this -> load -> model ('gatito_model');
		try {
			$id = $_POST['id'];
			$filter = isset ($_REQUEST['filter'] ) ? $_REQUEST['filter'] : '';

			$this -> gatito_model -> delete( $id );
			redirect(base_url().'gatito/list?filter='.$filter);
		}
		catch (Exception $e ) {
			frame($this, 'gatito/deleteERROR');
		}
	}	
	
	
	/**
	* Controller action UPDATE for controller gatito
	* autogenerated by CASE IGNITER
	*/
	public function update() {

		/*
		if (session_status () == PHP_SESSION_NONE) {session_start ();}
		$rol_ok = false;
		$login_rol = (isset($_SESSION['rol']) ? $_SESSION['rol']->nombre : null );
		if ($login_rol == 'admin') {$rol_ok = true;}

		if ( !$rol_ok ) {
			show_404();
		} 
		*/
		
		if (session_status () == PHP_SESSION_NONE) { session_start (); }
		$is_admin = ( isset($_SESSION['rol']) && $_SESSION['rol']->nombre == 'admin' );
		$data['body']['is_admin'] = $is_admin;
		$data['body']['filter'] = isset($_REQUEST['filter']) ? $_REQUEST['filter'] : '' ;
	
	
		$this->load->model('rol_model');
		$data['body']['rol'] = $this->rol_model->get_all();

		$this -> load -> model ('gatito_model');
		
		$id = (isset ($_POST['id']) ? $_POST['id'] : $_SESSION['id']);
		$data['body']['gatito'] = $this -> gatito_model -> get_by_id($id);
		
		frame($this, 'gatito/update', $data);
	}	
	
	/**
	* Controller action UPDATE POST for controller gatito
	* autogenerated by CASE IGNITER
	*/
	public function updatePost() {
	
		
		if (session_status () == PHP_SESSION_NONE) {session_start ();}
		$rol_ok = false;
		$login_rol = (isset($_SESSION['rol']) ? $_SESSION['rol']->nombre : null );
		if ($login_rol == 'admin') {$rol_ok = true;}

		if ( !$rol_ok ) {
			show_404();
		} 


		$this->load->model('gatito_model');
			
		$id = ( isset( $_POST['id']) ? $_POST['id'] : null );
		$nombre = ( isset( $_POST['nombre']) ? $_POST['nombre'] : null );
		$fecha = ( isset( $_POST['fecha']) ? $_POST['fecha'] : null );
		$loginname = ( isset( $_POST['loginname']) ? $_POST['loginname'] : null );
		$password = ( isset( $_POST['password']) ? $_POST['password'] : null );
		$roles = ( isset( $_POST['roles']) ? $_POST['roles'] : [] );
		if (session_status () == PHP_SESSION_NONE) {session_start ();}
		$is_admin = ( isset($_SESSION['rol']) && $_SESSION['rol']->nombre == 'admin' );		try {
			$this->gatito_model->update( $id, $nombre, $fecha, $loginname, $password, $roles, $is_admin );

			$filter = isset($_POST['filter']) ? $_POST['filter'] : '' ;
			redirect( base_url() . 'gatito/list?filter='.$filter );
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la gatito $nombre";
			frame($this,'gatito/create_message',$data);
		}	
	
	}
			
				
	
	/**
	* Controller action LOGIN for controller gatito
	* autogenerated by CASE IGNITER
	*/
	public function login() {
		frame($this,'gatito/login');
	}
	
	/**
	* Controller action LOGIN POST for controller gatito
	* autogenerated by CASE IGNITER
	*/
	public function loginPost() {
		$loginname = isset($_POST['loginname'])?$_POST['loginname']:null;
		$password = isset($_POST['password'])?$_POST['password']:null;

		$this->load->model('gatito_model');
		$user = $this->gatito_model->get_by_loginname($loginname);
		
		
		if ($user != null) {
			if ( password_verify($password, $user->password) ) {
					if (sizeof( $user->ownRolesList ) == 0) {
						throw new Exception("ERROR: No rol assgined");
					}
					$rol = $user->aggr('ownRolesList','rol')[0];
					if (session_status () == PHP_SESSION_NONE) {session_start ();}

					$_SESSION['user'] = $user;
					$_SESSION['rol'] = $rol;

					frame($this,'_home/index');
			} 
			else {
				throw new Exception("Password incorrecta");
			}
		}
		else {
			throw new Exception("Usuario inexistente");
		}
		
	}
		
	
	/**
	* Controller action LOGOUT for controller gatito
	* autogenerated by CASE IGNITER
	*/
	public function logout() {
		if (session_status () == PHP_SESSION_NONE) {
			session_start ();
		}
		session_destroy();
		redirect(base_url());
	}
		
	
	/**
	* Controller action CHANGE PASSWORD for controller gatito
	* autogenerated by CASE IGNITER
	*/
	public function changepwd() {
		if (session_status () == PHP_SESSION_NONE) {session_start ();}

		if (!isset($_SESSION['user'])) {
			show_404();
		}
		$data['body']['id'] = $_SESSION['user']->id;
		frame($this,'gatito/changepwd',$data);
	}
		
	
	/**
	* Controller action CHANGE PASSWORD POST for controller gatito
	* autogenerated by CASE IGNITER
	*/
	public function changepwdPost() {
		if (session_status () == PHP_SESSION_NONE) {session_start ();}
		
		if (!isset($_SESSION['user'])) {
			show_404();
		}

		$id = isset ($_POST['id']) ? $_POST['id'] : null ;
		$old_password = isset ($_POST['oldPwd']) ? $_POST['oldPwd'] : null ;
		$new_password = isset ($_POST['newPwd']) ? $_POST['newPwd'] : null ;

		if ($_SESSION['user']->id != $id) {
			show_404();
		}

		try {
			$this->load->model('gatito_model');
			$this->gatito_model->change_password($id,$old_password,$new_password);
			$this->load->library('session');
			$this->session->set_flashdata('id', $id);
			redirect(base_url().'gatito/update');
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al cambiar la contraseña";
			frame($this,'gatito/create_message',$data);
		}
	}
				}
?>