<?php
/**
* Controller code for grupo autogenerated by CASE IGNITER
*/
class grupo extends CI_Controller {

	/**
	* Controller action CREATE for controller grupo
	* autogenerated by CASE IGNITER
	*/
	public function create() {

		$this->load->model('usuario_model');
		$data['body']['usuario'] = $this->usuario_model->get_all();

		$this->load->model('imparticion_model');
		$data['body']['imparticion'] = $this->imparticion_model->get_all();

		$this->load->model('curso_model');
		$data['body']['curso'] = $this->curso_model->get_all();

		enmarcar($this, 'grupo/create', $data);
	}

	
	
	/**
	* Controller action CREATE POST for controller grupo
	* autogenerated by CASE IGNITER
	*/
	public function create_post() {
		
		$this->load->model('grupo_model');

		$nombre = ( isset( $_POST['nombre']) ? $_POST['nombre'] : null );
		$grreferencia = ( isset( $_POST['grreferencia']) ? $_POST['grreferencia'] : [] );
		$impartida = ( isset( $_POST['impartida']) ? $_POST['impartida'] : [] );
		$pertenece = ( isset( $_POST['pertenece']) ? $_POST['pertenece'] : [] );

		try {
			$id = $this->grupo_model->create( $nombre, $grreferencia, $impartida, $pertenece );
			$this->list_id($id);
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la grupo $nombre";
			$this->load->view('grupo/create_message',$data);
		}	
	
	}
				
				
	
	/**
	* Controller action LIST for controller grupo
	* autogenerated by CASE IGNITER
	*/
	public function list() {
		$this->load->model('grupo_model');
		$filter = isset($_POST['filter'])?$_POST['filter']:'';
		$data['body']['grupo'] = ($filter == '' ? $this->grupo_model->get_all() : $this->grupo_model->get_filtered( $filter ) );
		enmarcar($this, 'grupo/list', $data);
	}

	/**
	* Controller private function LIST_ID for controller grupo
	* autogenerated by CASE IGNITER
	*/
	private function list_id($id) {
		$this->load->model('grupo_model');
		$data['body']['grupo'] = [ $this->grupo_model->get_by_id($id) ];
		enmarcar($this, 'grupo/list', $data);
	}


	
	/**
	* Controller action DELETE for controller grupo
	* autogenerated by CASE IGNITER
	*/
	public function delete() {
		$this -> load -> model ('grupo_model');
		try {
			$id = $_POST['id'];
			$this -> grupo_model -> delete( $id );
			redirect(base_url().'grupo/list');
		}
		catch (Exception $e ) {
			enmarcar($this, 'grupo/deleteERROR');
		}
	}	
	
	
	/**
	* Controller action UPDATE for controller grupo
	* autogenerated by CASE IGNITER
	*/
	public function update() {	
	
		$this->load->model('usuario_model');
		$data['body']['usuario'] = $this->usuario_model->get_all();	
	
		$this->load->model('imparticion_model');
		$data['body']['imparticion'] = $this->imparticion_model->get_all();	
	
		$this->load->model('curso_model');
		$data['body']['curso'] = $this->curso_model->get_all();

		$this -> load -> model ('grupo_model');
		$id = $_POST['id'];
		$data['body']['grupo'] = $this -> grupo_model -> get_by_id($id);
		
		enmarcar($this, 'grupo/update', $data);
	}	
	
	/**
	* Controller action UPDATE POST for controller grupo
	* autogenerated by CASE IGNITER
	*/
	public function update_post() {
	
		$this->load->model('grupo_model');
			
		$id = ( isset( $_POST['id']) ? $_POST['id'] : null );
		$nombre = ( isset( $_POST['nombre']) ? $_POST['nombre'] : null );
		$grreferencia = ( isset( $_POST['grreferencia']) ? $_POST['grreferencia'] : [] );
		$impartida = ( isset( $_POST['impartida']) ? $_POST['impartida'] : [] );
		$pertenece = ( isset( $_POST['pertenece']) ? $_POST['pertenece'] : [] );

		try {
			$this->grupo_model->update( $id, $nombre, $grreferencia, $impartida, $pertenece );


			redirect( base_url() . 'grupo/list' );
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la grupo $nombre";
			$this->load->view('grupo/create_message',$data);
		}	
	
	}
			
			}
?>