<?php
/**
* Controller code for ies autogenerated by CASE IGNITER
*/
class ies extends CI_Controller {

	/**
	* Controller action CREATE for controller ies
	* autogenerated by CASE IGNITER
	*/
	public function create() {

		$this->load->model('cursoacademico_model');
		$data['body']['cursoacademico'] = $this->cursoacademico_model->get_all();

		enmarcar($this, 'ies/create', $data);
	}

	
	
	/**
	* Controller action CREATE POST for controller ies
	* autogenerated by CASE IGNITER
	*/
	public function create_post() {
		
		$this->load->model('ies_model');

		$nombre = ( isset( $_POST['nombre']) ? $_POST['nombre'] : null );
		$ocurre = ( isset( $_POST['ocurre']) ? $_POST['ocurre'] : [] );

		try {
			$id = $this->ies_model->create( $nombre, $ocurre );
			$this->list_id($id);
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la ies $nombre";
			$this->load->view('ies/create_message',$data);
		}	
	
	}
				
				
	
	/**
	* Controller action LIST for controller ies
	* autogenerated by CASE IGNITER
	*/
	public function list() {
		$this->load->model('ies_model');
		$filter = isset($_POST['filter'])?$_POST['filter']:'';
		$data['body']['ies'] = ($filter == '' ? $this->ies_model->get_all() : $this->ies_model->get_filtered( $filter ) );
		enmarcar($this, 'ies/list', $data);
	}

	/**
	* Controller private function LIST_ID for controller ies
	* autogenerated by CASE IGNITER
	*/
	private function list_id($id) {
		$this->load->model('ies_model');
		$data['body']['ies'] = [ $this->ies_model->get_by_id($id) ];
		enmarcar($this, 'ies/list', $data);
	}


	
	/**
	* Controller action DELETE for controller ies
	* autogenerated by CASE IGNITER
	*/
	public function delete() {
		$this -> load -> model ('ies_model');
		try {
			$id = $_POST['id'];
			$this -> ies_model -> delete( $id );
			redirect(base_url().'ies/list');
		}
		catch (Exception $e ) {
			enmarcar($this, 'ies/deleteERROR');
		}
	}	
	
	
	/**
	* Controller action UPDATE for controller ies
	* autogenerated by CASE IGNITER
	*/
	public function update() {	
	
		$this->load->model('cursoacademico_model');
		$data['body']['cursoacademico'] = $this->cursoacademico_model->get_all();

		$this -> load -> model ('ies_model');
		$id = $_POST['id'];
		$data['body']['ies'] = $this -> ies_model -> get_by_id($id);
		
		enmarcar($this, 'ies/update', $data);
	}	
	
	/**
	* Controller action UPDATE POST for controller ies
	* autogenerated by CASE IGNITER
	*/
	public function update_post() {
	
		$this->load->model('ies_model');
			
		$id = ( isset( $_POST['id']) ? $_POST['id'] : null );
		$nombre = ( isset( $_POST['nombre']) ? $_POST['nombre'] : null );
		$ocurre = ( isset( $_POST['ocurre']) ? $_POST['ocurre'] : [] );

		try {
			$this->ies_model->update( $id, $nombre, $ocurre );


			redirect( base_url() . 'ies/list' );
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la ies $nombre";
			$this->load->view('ies/create_message',$data);
		}	
	
	}
			
			}
?>