<?php
/**
* Controller code for imparticion autogenerated by CASE IGNITER
*/
class imparticion extends CI_Controller {

	/**
	* Controller action CREATE for controller imparticion
	* autogenerated by CASE IGNITER
	*/
	public function create() {

		$this->load->model('usuario_model');
		$data['body']['usuario'] = $this->usuario_model->get_all();

		$this->load->model('grupo_model');
		$data['body']['grupo'] = $this->grupo_model->get_all();

		$this->load->model('asignatura_model');
		$data['body']['asignatura'] = $this->asignatura_model->get_all();

		$this->load->model('plantillaencuesta_model');
		$data['body']['plantillaencuesta'] = $this->plantillaencuesta_model->get_all();

		$this->load->model('encuesta_model');
		$data['body']['encuesta'] = $this->encuesta_model->get_all();

		$this->load->model('cursoacademico_model');
		$data['body']['cursoacademico'] = $this->cursoacademico_model->get_all();

		enmarcar($this, 'imparticion/create', $data);
	}

	
	
	/**
	* Controller action CREATE POST for controller imparticion
	* autogenerated by CASE IGNITER
	*/
	public function create_post() {
		
		$this->load->model('imparticion_model');

		$nombre = ( isset( $_POST['nombre']) ? $_POST['nombre'] : null );
		$desarrolla = ( isset( $_POST['desarrolla']) ? $_POST['desarrolla'] : [] );
		$impartida = ( isset( $_POST['impartida']) ? $_POST['impartida'] : [] );
		$refierea = ( isset( $_POST['refierea']) ? $_POST['refierea'] : [] );
		$asociaa = ( isset( $_POST['asociaa']) ? $_POST['asociaa'] : [] );
		$realizada = ( isset( $_POST['realizada']) ? $_POST['realizada'] : [] );
		$tieneim = ( isset( $_POST['tieneim']) ? $_POST['tieneim'] : [] );

		try {
			$id = $this->imparticion_model->create( $nombre, $desarrolla, $impartida, $refierea, $asociaa, $realizada, $tieneim );
			$this->list_id($id);
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la imparticion $nombre";
			$this->load->view('imparticion/create_message',$data);
		}	
	
	}
				
				
	
	/**
	* Controller action LIST for controller imparticion
	* autogenerated by CASE IGNITER
	*/
	public function list() {
		$this->load->model('imparticion_model');
		$filter = isset($_POST['filter'])?$_POST['filter']:'';
		$data['body']['imparticion'] = ($filter == '' ? $this->imparticion_model->get_all() : $this->imparticion_model->get_filtered( $filter ) );
		enmarcar($this, 'imparticion/list', $data);
	}

	/**
	* Controller private function LIST_ID for controller imparticion
	* autogenerated by CASE IGNITER
	*/
	private function list_id($id) {
		$this->load->model('imparticion_model');
		$data['body']['imparticion'] = [ $this->imparticion_model->get_by_id($id) ];
		enmarcar($this, 'imparticion/list', $data);
	}


	
	/**
	* Controller action DELETE for controller imparticion
	* autogenerated by CASE IGNITER
	*/
	public function delete() {
		$this -> load -> model ('imparticion_model');
		try {
			$id = $_POST['id'];
			$this -> imparticion_model -> delete( $id );
			redirect(base_url().'imparticion/list');
		}
		catch (Exception $e ) {
			enmarcar($this, 'imparticion/deleteERROR');
		}
	}	
	
	
	/**
	* Controller action UPDATE for controller imparticion
	* autogenerated by CASE IGNITER
	*/
	public function update() {	
	
		$this->load->model('usuario_model');
		$data['body']['usuario'] = $this->usuario_model->get_all();	
	
		$this->load->model('grupo_model');
		$data['body']['grupo'] = $this->grupo_model->get_all();	
	
		$this->load->model('asignatura_model');
		$data['body']['asignatura'] = $this->asignatura_model->get_all();	
	
		$this->load->model('plantillaencuesta_model');
		$data['body']['plantillaencuesta'] = $this->plantillaencuesta_model->get_all();	
	
		$this->load->model('encuesta_model');
		$data['body']['encuesta'] = $this->encuesta_model->get_all();	
	
		$this->load->model('cursoacademico_model');
		$data['body']['cursoacademico'] = $this->cursoacademico_model->get_all();

		$this -> load -> model ('imparticion_model');
		$id = $_POST['id'];
		$data['body']['imparticion'] = $this -> imparticion_model -> get_by_id($id);
		
		enmarcar($this, 'imparticion/update', $data);
	}	
	
	/**
	* Controller action UPDATE POST for controller imparticion
	* autogenerated by CASE IGNITER
	*/
	public function update_post() {
	
		$this->load->model('imparticion_model');
			
		$id = ( isset( $_POST['id']) ? $_POST['id'] : null );
		$nombre = ( isset( $_POST['nombre']) ? $_POST['nombre'] : null );
		$desarrolla = ( isset( $_POST['desarrolla']) ? $_POST['desarrolla'] : [] );
		$impartida = ( isset( $_POST['impartida']) ? $_POST['impartida'] : [] );
		$refierea = ( isset( $_POST['refierea']) ? $_POST['refierea'] : [] );
		$asociaa = ( isset( $_POST['asociaa']) ? $_POST['asociaa'] : [] );
		$realizada = ( isset( $_POST['realizada']) ? $_POST['realizada'] : [] );
		$tieneim = ( isset( $_POST['tieneim']) ? $_POST['tieneim'] : [] );

		try {
			$this->imparticion_model->update( $id, $nombre, $desarrolla, $impartida, $refierea, $asociaa, $realizada, $tieneim );


			redirect( base_url() . 'imparticion/list' );
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la imparticion $nombre";
			$this->load->view('imparticion/create_message',$data);
		}	
	
	}
			
			}
?>