<?php
/**
* Controller code for mascota autogenerated by CASE IGNITER
*/
class mascota extends CI_Controller {

	/**
	* Controller action CREATE for controller mascota
	* autogenerated by CASE IGNITER
	*/
	public function create() {

		$data = [];

		enmarcar($this, 'mascota/create', $data);
	}

	
	
	/**
	* Controller action CREATE POST for controller mascota
	* autogenerated by CASE IGNITER
	*/
	public function create_post() {
		
		$this->load->model('mascota_model');

		$nombre = ( isset( $_POST['nombre']) ? $_POST['nombre'] : null );

		try {
			$this->mascota_model->create( $nombre );
			$data['status'] = 'ok';
			$data['message'] = "Mascota $nombre creado/a correctamente";
			$this->load->view('mascota/create_message',$data);
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = 'Error al crear el/la mascota $nombre';
			$this->load->view('mascota/create_message',$data);
		}	
	
	}
				
					public function list() {
		$this->load->model('mascota_model');
		$filter = isset($_POST['filter'])?$_POST['filter']:'';
		$data['body']['mascota'] = ($filter == '' ? $this->mascota_model->get_all() : $this->mascota_model->get_filtered( $filter ) );
		enmarcar($this, 'mascota/list', $data);
	}}
?>