<?php
/**
* Controller code for pais autogenerated by CASE IGNITER
*/
class pais extends CI_Controller {

	/**
	* Controller action CREATE for controller pais
	* autogenerated by CASE IGNITER
	*/
	public function create() {

		$this->load->model('persona_model');
		$data['body']['persona'] = $this->persona_model->get_all();

		enmarcar($this, 'pais/create', $data);
	}

	
	
	/**
	* Controller action CREATE POST for controller pais
	* autogenerated by CASE IGNITER
	*/
	public function create_post() {
		
		$this->load->model('pais_model');

		$nombre = ( isset( $_POST['nombre']) ? $_POST['nombre'] : null );
		$pais_nacimiento = ( isset( $_POST['pais_nacimiento']) ? $_POST['pais_nacimiento'] : [] );

		try {
			$this->pais_model->create( $nombre, $pais_nacimiento );
			$data['status'] = 'ok';
			$data['message'] = "Pais $nombre creado/a correctamente";
			$this->load->view('pais/create_message',$data);
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = 'Error al crear el/la pais $nombre';
			$this->load->view('pais/create_message',$data);
		}	
	
	}
				
					public function list() {
		$this->load->model('pais_model');
		$filter = isset($_POST['filter'])?$_POST['filter']:'';
		$data['body']['pais'] = ($filter == '' ? $this->pais_model->get_all() : $this->pais_model->get_filtered( $filter ) );
		enmarcar($this, 'pais/list', $data);
	}}
?>