<?php
/**
* Controller code for perrito autogenerated by CASE IGNITER
*/
class perrito extends CI_Controller {

	/**
	* Controller action CREATE for controller perrito
	* autogenerated by CASE IGNITER
	*/
	public function create() {

		$data['body']['filter'] = isset($_REQUEST['filter']) ? $_REQUEST['filter'] : '' ;

		$this->load->model('rol_model');
		$data['body']['rol'] = $this->rol_model->get_all();
		enmarcar($this, 'perrito/create', $data);
	}

	
	
	/**
	* Controller action CREATE POST for controller perrito
	* autogenerated by CASE IGNITER
	*/
	public function create_post() {
		
		$this->load->model('perrito_model');

		$nombre = ( isset( $_POST['nombre']) ? $_POST['nombre'] : null );
		$loginname = ( isset( $_POST['loginname']) ? $_POST['loginname'] : null );
		$password = ( isset( $_POST['password']) ? $_POST['password'] : null );
		$roles = ( isset( $_POST['roles']) ? $_POST['roles'] : [] );

		try {
			$id = $this->perrito_model->create( $nombre, $loginname, $password, $roles );
			$this->list_id($id);
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la perrito $nombre";
			$this->load->view('perrito/create_message',$data);
		}	
	
	}
				
				
	
	/**
	* Controller action LIST for controller perrito
	* autogenerated by CASE IGNITER
	*/
	public function list() {
		$this->load->model('perrito_model');
		$filter = isset($_REQUEST['filter'])?$_REQUEST['filter']:'';
		$data['body']['perrito'] = ($filter == '' ? $this->perrito_model->get_all() : $this->perrito_model->get_filtered( $filter ) );
		$data['body']['filter'] = $filter ;
		enmarcar($this, 'perrito/list', $data);
	}

	/**
	* Controller private function LIST_ID for controller perrito
	* autogenerated by CASE IGNITER
	*/
	private function list_id($id) {
		$this->load->model('perrito_model');
		$data['body']['perrito'] = [ $this->perrito_model->get_by_id($id) ];
		enmarcar($this, 'perrito/list', $data);
	}


	
	/**
	* Controller action DELETE for controller perrito
	* autogenerated by CASE IGNITER
	*/
	public function delete() {
		$this -> load -> model ('perrito_model');
		try {
			$id = $_POST['id'];
			$filter = isset ($_REQUEST['filter'] ) ? $_REQUEST['filter'] : '';

			$this -> perrito_model -> delete( $id );
			redirect(base_url().'perrito/list?filter='.$filter);
		}
		catch (Exception $e ) {
			enmarcar($this, 'perrito/deleteERROR');
		}
	}	
	
	
	/**
	* Controller action UPDATE for controller perrito
	* autogenerated by CASE IGNITER
	*/
	public function update() {

		$data['body']['filter'] = isset($_REQUEST['filter']) ? $_REQUEST['filter'] : '' ;
	
	
		$this->load->model('rol_model');
		$data['body']['rol'] = $this->rol_model->get_all();

		$this -> load -> model ('perrito_model');
		$id = $_POST['id'];
		$data['body']['perrito'] = $this -> perrito_model -> get_by_id($id);
		
		enmarcar($this, 'perrito/update', $data);
	}	
	
	/**
	* Controller action UPDATE POST for controller perrito
	* autogenerated by CASE IGNITER
	*/
	public function update_post() {
	
		$this->load->model('perrito_model');
			
		$id = ( isset( $_POST['id']) ? $_POST['id'] : null );
		$nombre = ( isset( $_POST['nombre']) ? $_POST['nombre'] : null );
		$loginname = ( isset( $_POST['loginname']) ? $_POST['loginname'] : null );
		$password = ( isset( $_POST['password']) ? $_POST['password'] : null );
		$roles = ( isset( $_POST['roles']) ? $_POST['roles'] : [] );

		try {
			$this->perrito_model->update( $id, $nombre, $loginname, $password, $roles );

			$filter = isset($_POST['filter']) ? $_POST['filter'] : '' ;
			redirect( base_url() . 'perrito/list?filter='.$filter );
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la perrito $nombre";
			$this->load->view('perrito/create_message',$data);
		}	
	
	}
			
				
	
	/**
	* Controller action LOGIN for controller perrito
	* autogenerated by CASE IGNITER
	*/
	public function login() {
		$this->load->model('rol_model');
		$data['body']['rol'] = $this->rol_model->get_all();
		
		enmarcar($this,'perrito/login',$data);
	}
	
	/**
	* Controller action LOGIN POST for controller perrito
	* autogenerated by CASE IGNITER
	*/
	public function loginPost() {
		$loginname = isset($_POST['loginname'])?$_POST['loginname']:null;
		$password = isset($_POST['password'])?$_POST['password']:null;
		$rol = isset($_POST['rol'])?$_POST['rol']:null;

		$this->load->model('perrito_model');
		$user = $this->perrito_model->get_by_loginname($loginname);
		
		if ($user != null) {
			if ( password_verify($password, $user->password) ) {
				$rol_ok = false;
				$rol_id = 0;
				foreach ($user->aggr('ownRolesList', 'rol' )  as $r ) {
					if ($r->id == $rol) {
						$rol_ok = true;
						$rol_id = $r->id;
					}
				}
				if ($rol_ok ) {
					if (session_status () == PHP_SESSION_NONE) {session_start ();}
					$_SESSION['user'] = $user;
					$this->load->model('rol_model');
					$rol_used = $this->rol_model->get_by_id($rol_id);

					$_SESSION['rol'] = $rol_used;
					enmarcar($this,'_home/index');
				}
				else {
					throw new Exception("Rol incorrecta");
				}
			} 
			else {
				throw new Exception("Password incorrecta");
			}
		}
		else {
			throw new Exception("Usuario inexistente");
		}
		
	}
		
	
	/**
	* Controller action LOGOUT for controller perrito
	* autogenerated by CASE IGNITER
	*/
	public function logout() {
		if (session_status () == PHP_SESSION_NONE) {
			session_start ();
		}
		session_destroy();
		enmarcar($this,'_home/index');
	}
	}
?>