<?php
/**
* Controller code for persona autogenerated by CASE IGNITER
*/
class persona extends CI_Controller {

	/**
	* Controller action CREATE for controller persona
	* autogenerated by CASE IGNITER
	*/
	public function create() {

		$this->load->model('mascota_model');
		$data['body']['mascota'] = $this->mascota_model->get_all();

		$this->load->model('pais_model');
		$data['body']['pais'] = $this->pais_model->get_all();

		$this->load->model('aficion_model');
		$data['body']['aficion'] = $this->aficion_model->get_all();

		enmarcar($this, 'persona/create', $data);
	}

	
	
	/**
	* Controller action CREATE POST for controller persona
	* autogenerated by CASE IGNITER
	*/
	public function create_post() {
		
		$this->load->model('persona_model');

		$nombre = ( isset( $_POST['nombre']) ? $_POST['nombre'] : null );
		$fechanacimiento = ( isset( $_POST['fechanacimiento']) ? $_POST['fechanacimiento'] : null );
		$peso = ( isset( $_POST['peso']) ? $_POST['peso'] : null );
		$amo = ( isset( $_POST['amo']) ? $_POST['amo'] : null );
		$paisnacimiento = ( isset( $_POST['paisnacimiento']) ? $_POST['paisnacimiento'] : null );
		$gusta = ( isset( $_POST['gusta']) ? $_POST['gusta'] : [] );
		$odia = ( isset( $_POST['odia']) ? $_POST['odia'] : [] );
		$expertoen = ( isset( $_POST['expertoen']) ? $_POST['expertoen'] : [] );
		$inutilen = ( isset( $_POST['inutilen']) ? $_POST['inutilen'] : [] );

		try {
			$this->persona_model->create( $nombre, $fechanacimiento, $peso, $amo, $paisnacimiento, $gusta, $odia, $expertoen, $inutilen );
			$data['status'] = 'ok';
			$data['message'] = "Persona $nombre creado/a correctamente";
			$this->load->view('persona/create_message',$data);
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la persona $nombre";
			$this->load->view('persona/create_message',$data);
		}	
	
	}
				
				
	
	/**
	* Controller action LIST for controller persona
	* autogenerated by CASE IGNITER
	*/
	public function list() {
		$this->load->model('persona_model');
		$filter = isset($_POST['filter'])?$_POST['filter']:'';
		$data['body']['persona'] = ($filter == '' ? $this->persona_model->get_all() : $this->persona_model->get_filtered( $filter ) );
		enmarcar($this, 'persona/list', $data);
	}

	
	/**
	* Controller action DELETE for controller persona
	* autogenerated by CASE IGNITER
	*/
	public function delete() {
		$this -> load -> model ('persona_model');
		try {
			$id = $_POST['id'];
			$this -> persona_model -> delete( $id );
			redirect(base_url().'persona/list');
		}
		catch (Exception $e ) {
			enmarcar($this, 'persona/deleteERROR');
		}
	}	
	
	
	/**
	* Controller action UPDATE for controller persona
	* autogenerated by CASE IGNITER
	*/
	public function update() {	
	
		$this->load->model('mascota_model');
		$data['body']['mascota'] = $this->mascota_model->get_all();	
	
		$this->load->model('pais_model');
		$data['body']['pais'] = $this->pais_model->get_all();	
	
		$this->load->model('aficion_model');
		$data['body']['aficion'] = $this->aficion_model->get_all();

		$this -> load -> model ('persona_model');
		$id = $_POST['id'];
		$data['body']['persona'] = $this -> persona_model -> get_by_id($id);
		
		enmarcar($this, 'persona/update', $data);
	}	
	
	/**
	* Controller action UPDATE POST for controller persona
	* autogenerated by CASE IGNITER
	*/
	public function update_post() {
	
		$this->load->model('persona_model');
			
		$id = ( isset( $_POST['id']) ? $_POST['id'] : null );
		$nombre = ( isset( $_POST['nombre']) ? $_POST['nombre'] : null );
		$fechanacimiento = ( isset( $_POST['fechanacimiento']) ? $_POST['fechanacimiento'] : null );
		$peso = ( isset( $_POST['peso']) ? $_POST['peso'] : null );
		$amo = ( isset( $_POST['amo']) ? $_POST['amo'] : null );
		$paisnacimiento = ( isset( $_POST['paisnacimiento']) ? $_POST['paisnacimiento'] : null );
		$gusta = ( isset( $_POST['gusta']) ? $_POST['gusta'] : [] );
		$odia = ( isset( $_POST['odia']) ? $_POST['odia'] : [] );
		$expertoen = ( isset( $_POST['expertoen']) ? $_POST['expertoen'] : [] );
		$inutilen = ( isset( $_POST['inutilen']) ? $_POST['inutilen'] : [] );

		try {
			$this->persona_model->update( $id, $nombre, $fechanacimiento, $peso, $amo, $paisnacimiento, $gusta, $odia, $expertoen, $inutilen );


			redirect( base_url() . 'persona/list' );
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la persona $nombre";
			$this->load->view('persona/create_message',$data);
		}	
	
	}
			
			}
?>