<?php
/**
* Controller code for plantillaencuesta autogenerated by CASE IGNITER
*/
class plantillaencuesta extends CI_Controller {

	/**
	* Controller action CREATE for controller plantillaencuesta
	* autogenerated by CASE IGNITER
	*/
	public function create() {

		$this->load->model('imparticion_model');
		$data['body']['imparticion'] = $this->imparticion_model->get_all();

		$this->load->model('preguntacerrada_model');
		$data['body']['preguntacerrada'] = $this->preguntacerrada_model->get_all();

		$this->load->model('preguntaabierta_model');
		$data['body']['preguntaabierta'] = $this->preguntaabierta_model->get_all();

		$this->load->model('encuesta_model');
		$data['body']['encuesta'] = $this->encuesta_model->get_all();

		enmarcar($this, 'plantillaencuesta/create', $data);
	}

	
	
	/**
	* Controller action CREATE POST for controller plantillaencuesta
	* autogenerated by CASE IGNITER
	*/
	public function create_post() {
		
		$this->load->model('plantillaencuesta_model');

		$nombre = ( isset( $_POST['nombre']) ? $_POST['nombre'] : null );
		$asociaa = ( isset( $_POST['asociaa']) ? $_POST['asociaa'] : [] );
		$componepc = ( isset( $_POST['componepc']) ? $_POST['componepc'] : [] );
		$componepa = ( isset( $_POST['componepa']) ? $_POST['componepa'] : [] );
		$acercade = ( isset( $_POST['acercade']) ? $_POST['acercade'] : [] );

		try {
			$id = $this->plantillaencuesta_model->create( $nombre, $asociaa, $componepc, $componepa, $acercade );
			$this->list_id($id);
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la plantillaencuesta $nombre";
			$this->load->view('plantillaencuesta/create_message',$data);
		}	
	
	}
				
				
	
	/**
	* Controller action LIST for controller plantillaencuesta
	* autogenerated by CASE IGNITER
	*/
	public function list() {
		$this->load->model('plantillaencuesta_model');
		$filter = isset($_POST['filter'])?$_POST['filter']:'';
		$data['body']['plantillaencuesta'] = ($filter == '' ? $this->plantillaencuesta_model->get_all() : $this->plantillaencuesta_model->get_filtered( $filter ) );
		enmarcar($this, 'plantillaencuesta/list', $data);
	}

	/**
	* Controller private function LIST_ID for controller plantillaencuesta
	* autogenerated by CASE IGNITER
	*/
	private function list_id($id) {
		$this->load->model('plantillaencuesta_model');
		$data['body']['plantillaencuesta'] = [ $this->plantillaencuesta_model->get_by_id($id) ];
		enmarcar($this, 'plantillaencuesta/list', $data);
	}


	
	/**
	* Controller action DELETE for controller plantillaencuesta
	* autogenerated by CASE IGNITER
	*/
	public function delete() {
		$this -> load -> model ('plantillaencuesta_model');
		try {
			$id = $_POST['id'];
			$this -> plantillaencuesta_model -> delete( $id );
			redirect(base_url().'plantillaencuesta/list');
		}
		catch (Exception $e ) {
			enmarcar($this, 'plantillaencuesta/deleteERROR');
		}
	}	
	
	
	/**
	* Controller action UPDATE for controller plantillaencuesta
	* autogenerated by CASE IGNITER
	*/
	public function update() {	
	
		$this->load->model('imparticion_model');
		$data['body']['imparticion'] = $this->imparticion_model->get_all();	
	
		$this->load->model('preguntacerrada_model');
		$data['body']['preguntacerrada'] = $this->preguntacerrada_model->get_all();	
	
		$this->load->model('preguntaabierta_model');
		$data['body']['preguntaabierta'] = $this->preguntaabierta_model->get_all();	
	
		$this->load->model('encuesta_model');
		$data['body']['encuesta'] = $this->encuesta_model->get_all();

		$this -> load -> model ('plantillaencuesta_model');
		$id = $_POST['id'];
		$data['body']['plantillaencuesta'] = $this -> plantillaencuesta_model -> get_by_id($id);
		
		enmarcar($this, 'plantillaencuesta/update', $data);
	}	
	
	/**
	* Controller action UPDATE POST for controller plantillaencuesta
	* autogenerated by CASE IGNITER
	*/
	public function update_post() {
	
		$this->load->model('plantillaencuesta_model');
			
		$id = ( isset( $_POST['id']) ? $_POST['id'] : null );
		$nombre = ( isset( $_POST['nombre']) ? $_POST['nombre'] : null );
		$asociaa = ( isset( $_POST['asociaa']) ? $_POST['asociaa'] : [] );
		$componepc = ( isset( $_POST['componepc']) ? $_POST['componepc'] : [] );
		$componepa = ( isset( $_POST['componepa']) ? $_POST['componepa'] : [] );
		$acercade = ( isset( $_POST['acercade']) ? $_POST['acercade'] : [] );

		try {
			$this->plantillaencuesta_model->update( $id, $nombre, $asociaa, $componepc, $componepa, $acercade );


			redirect( base_url() . 'plantillaencuesta/list' );
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la plantillaencuesta $nombre";
			$this->load->view('plantillaencuesta/create_message',$data);
		}	
	
	}
			
			}
?>