<?php
/**
* Controller code for preguntacerrada autogenerated by CASE IGNITER
*/
class preguntacerrada extends CI_Controller {

	/**
	* Controller action CREATE for controller preguntacerrada
	* autogenerated by CASE IGNITER
	*/
	public function create() {

		$this->load->model('asignatura_model');
		$data['body']['asignatura'] = $this->asignatura_model->get_all();

		$this->load->model('plantillaencuesta_model');
		$data['body']['plantillaencuesta'] = $this->plantillaencuesta_model->get_all();

		$this->load->model('respuestacerrada_model');
		$data['body']['respuestacerrada'] = $this->respuestacerrada_model->get_all();

		$this->load->model('categoria_model');
		$data['body']['categoria'] = $this->categoria_model->get_all();

		enmarcar($this, 'preguntacerrada/create', $data);
	}

	
	
	/**
	* Controller action CREATE POST for controller preguntacerrada
	* autogenerated by CASE IGNITER
	*/
	public function create_post() {
		
		$this->load->model('preguntacerrada_model');

		$nombre = ( isset( $_POST['nombre']) ? $_POST['nombre'] : null );
		$enunciado = ( isset( $_POST['enunciado']) ? $_POST['enunciado'] : null );
		$enunciadofacil = ( isset( $_POST['enunciadofacil']) ? $_POST['enunciadofacil'] : null );
		$min = ( isset( $_POST['min']) ? $_POST['min'] : null );
		$max = ( isset( $_POST['max']) ? $_POST['max'] : null );
		$versacerrada = ( isset( $_POST['versacerrada']) ? $_POST['versacerrada'] : [] );
		$componepc = ( isset( $_POST['componepc']) ? $_POST['componepc'] : [] );
		$respuestasrc = ( isset( $_POST['respuestasrc']) ? $_POST['respuestasrc'] : [] );
		$contienepc = ( isset( $_POST['contienepc']) ? $_POST['contienepc'] : [] );

		try {
			$id = $this->preguntacerrada_model->create( $nombre, $enunciado, $enunciadofacil, $min, $max, $versacerrada, $componepc, $respuestasrc, $contienepc );
			$this->list_id($id);
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la preguntacerrada $nombre";
			$this->load->view('preguntacerrada/create_message',$data);
		}	
	
	}
				
				
	
	/**
	* Controller action LIST for controller preguntacerrada
	* autogenerated by CASE IGNITER
	*/
	public function list() {
		$this->load->model('preguntacerrada_model');
		$filter = isset($_POST['filter'])?$_POST['filter']:'';
		$data['body']['preguntacerrada'] = ($filter == '' ? $this->preguntacerrada_model->get_all() : $this->preguntacerrada_model->get_filtered( $filter ) );
		enmarcar($this, 'preguntacerrada/list', $data);
	}

	/**
	* Controller private function LIST_ID for controller preguntacerrada
	* autogenerated by CASE IGNITER
	*/
	private function list_id($id) {
		$this->load->model('preguntacerrada_model');
		$data['body']['preguntacerrada'] = [ $this->preguntacerrada_model->get_by_id($id) ];
		enmarcar($this, 'preguntacerrada/list', $data);
	}


	
	/**
	* Controller action DELETE for controller preguntacerrada
	* autogenerated by CASE IGNITER
	*/
	public function delete() {
		$this -> load -> model ('preguntacerrada_model');
		try {
			$id = $_POST['id'];
			$this -> preguntacerrada_model -> delete( $id );
			redirect(base_url().'preguntacerrada/list');
		}
		catch (Exception $e ) {
			enmarcar($this, 'preguntacerrada/deleteERROR');
		}
	}	
	
	
	/**
	* Controller action UPDATE for controller preguntacerrada
	* autogenerated by CASE IGNITER
	*/
	public function update() {	
	
		$this->load->model('asignatura_model');
		$data['body']['asignatura'] = $this->asignatura_model->get_all();	
	
		$this->load->model('plantillaencuesta_model');
		$data['body']['plantillaencuesta'] = $this->plantillaencuesta_model->get_all();	
	
		$this->load->model('respuestacerrada_model');
		$data['body']['respuestacerrada'] = $this->respuestacerrada_model->get_all();	
	
		$this->load->model('categoria_model');
		$data['body']['categoria'] = $this->categoria_model->get_all();

		$this -> load -> model ('preguntacerrada_model');
		$id = $_POST['id'];
		$data['body']['preguntacerrada'] = $this -> preguntacerrada_model -> get_by_id($id);
		
		enmarcar($this, 'preguntacerrada/update', $data);
	}	
	
	/**
	* Controller action UPDATE POST for controller preguntacerrada
	* autogenerated by CASE IGNITER
	*/
	public function update_post() {
	
		$this->load->model('preguntacerrada_model');
			
		$id = ( isset( $_POST['id']) ? $_POST['id'] : null );
		$nombre = ( isset( $_POST['nombre']) ? $_POST['nombre'] : null );
		$enunciado = ( isset( $_POST['enunciado']) ? $_POST['enunciado'] : null );
		$enunciadofacil = ( isset( $_POST['enunciadofacil']) ? $_POST['enunciadofacil'] : null );
		$min = ( isset( $_POST['min']) ? $_POST['min'] : null );
		$max = ( isset( $_POST['max']) ? $_POST['max'] : null );
		$versacerrada = ( isset( $_POST['versacerrada']) ? $_POST['versacerrada'] : [] );
		$componepc = ( isset( $_POST['componepc']) ? $_POST['componepc'] : [] );
		$respuestasrc = ( isset( $_POST['respuestasrc']) ? $_POST['respuestasrc'] : [] );
		$contienepc = ( isset( $_POST['contienepc']) ? $_POST['contienepc'] : [] );

		try {
			$this->preguntacerrada_model->update( $id, $nombre, $enunciado, $enunciadofacil, $min, $max, $versacerrada, $componepc, $respuestasrc, $contienepc );


			redirect( base_url() . 'preguntacerrada/list' );
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la preguntacerrada $nombre";
			$this->load->view('preguntacerrada/create_message',$data);
		}	
	
	}
			
			}
?>