<?php
/**
* Controller code for preguntaabierta autogenerated by CASE IGNITER
*/
class preguntaabierta extends CI_Controller {

	/**
	* Controller action CREATE for controller preguntaabierta
	* autogenerated by CASE IGNITER
	*/
	public function create() {

		$this->load->model('asignatura_model');
		$data['body']['asignatura'] = $this->asignatura_model->get_all();

		$this->load->model('plantillaencuesta_model');
		$data['body']['plantillaencuesta'] = $this->plantillaencuesta_model->get_all();

		$this->load->model('respuestaabierta_model');
		$data['body']['respuestaabierta'] = $this->respuestaabierta_model->get_all();

		$this->load->model('categoria_model');
		$data['body']['categoria'] = $this->categoria_model->get_all();

		enmarcar($this, 'preguntaabierta/create', $data);
	}

	
	
	/**
	* Controller action CREATE POST for controller preguntaabierta
	* autogenerated by CASE IGNITER
	*/
	public function create_post() {
		
		$this->load->model('preguntaabierta_model');

		$enunciado = ( isset( $_POST['enunciado']) ? $_POST['enunciado'] : null );
		$enunciadofacil = ( isset( $_POST['enunciadofacil']) ? $_POST['enunciadofacil'] : null );
		$versaabierta = ( isset( $_POST['versaabierta']) ? $_POST['versaabierta'] : [] );
		$componepa = ( isset( $_POST['componepa']) ? $_POST['componepa'] : [] );
		$respuestasra = ( isset( $_POST['respuestasra']) ? $_POST['respuestasra'] : [] );
		$contienepa = ( isset( $_POST['contienepa']) ? $_POST['contienepa'] : [] );

		try {
			$id = $this->preguntaabierta_model->create( $enunciado, $enunciadofacil, $versaabierta, $componepa, $respuestasra, $contienepa );
			$this->list_id($id);
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la preguntaabierta $enunciado";
			$this->load->view('preguntaabierta/create_message',$data);
		}	
	
	}
				
				
	
	/**
	* Controller action LIST for controller preguntaabierta
	* autogenerated by CASE IGNITER
	*/
	public function list() {
		$this->load->model('preguntaabierta_model');
		$filter = isset($_POST['filter'])?$_POST['filter']:'';
		$data['body']['preguntaabierta'] = ($filter == '' ? $this->preguntaabierta_model->get_all() : $this->preguntaabierta_model->get_filtered( $filter ) );
		enmarcar($this, 'preguntaabierta/list', $data);
	}

	/**
	* Controller private function LIST_ID for controller preguntaabierta
	* autogenerated by CASE IGNITER
	*/
	private function list_id($id) {
		$this->load->model('preguntaabierta_model');
		$data['body']['preguntaabierta'] = [ $this->preguntaabierta_model->get_by_id($id) ];
		enmarcar($this, 'preguntaabierta/list', $data);
	}


	
	/**
	* Controller action DELETE for controller preguntaabierta
	* autogenerated by CASE IGNITER
	*/
	public function delete() {
		$this -> load -> model ('preguntaabierta_model');
		try {
			$id = $_POST['id'];
			$this -> preguntaabierta_model -> delete( $id );
			redirect(base_url().'preguntaabierta/list');
		}
		catch (Exception $e ) {
			enmarcar($this, 'preguntaabierta/deleteERROR');
		}
	}	
	
	
	/**
	* Controller action UPDATE for controller preguntaabierta
	* autogenerated by CASE IGNITER
	*/
	public function update() {	
	
		$this->load->model('asignatura_model');
		$data['body']['asignatura'] = $this->asignatura_model->get_all();	
	
		$this->load->model('plantillaencuesta_model');
		$data['body']['plantillaencuesta'] = $this->plantillaencuesta_model->get_all();	
	
		$this->load->model('respuestaabierta_model');
		$data['body']['respuestaabierta'] = $this->respuestaabierta_model->get_all();	
	
		$this->load->model('categoria_model');
		$data['body']['categoria'] = $this->categoria_model->get_all();

		$this -> load -> model ('preguntaabierta_model');
		$id = $_POST['id'];
		$data['body']['preguntaabierta'] = $this -> preguntaabierta_model -> get_by_id($id);
		
		enmarcar($this, 'preguntaabierta/update', $data);
	}	
	
	/**
	* Controller action UPDATE POST for controller preguntaabierta
	* autogenerated by CASE IGNITER
	*/
	public function update_post() {
	
		$this->load->model('preguntaabierta_model');
			
		$id = ( isset( $_POST['id']) ? $_POST['id'] : null );
		$enunciado = ( isset( $_POST['enunciado']) ? $_POST['enunciado'] : null );
		$enunciadofacil = ( isset( $_POST['enunciadofacil']) ? $_POST['enunciadofacil'] : null );
		$versaabierta = ( isset( $_POST['versaabierta']) ? $_POST['versaabierta'] : [] );
		$componepa = ( isset( $_POST['componepa']) ? $_POST['componepa'] : [] );
		$respuestasra = ( isset( $_POST['respuestasra']) ? $_POST['respuestasra'] : [] );
		$contienepa = ( isset( $_POST['contienepa']) ? $_POST['contienepa'] : [] );

		try {
			$this->preguntaabierta_model->update( $id, $enunciado, $enunciadofacil, $versaabierta, $componepa, $respuestasra, $contienepa );


			redirect( base_url() . 'preguntaabierta/list' );
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la preguntaabierta $enunciado";
			$this->load->view('preguntaabierta/create_message',$data);
		}	
	
	}
			
			}
?>