<?php
/**
* Controller code for respuestaabierta autogenerated by CASE IGNITER
*/
class respuestaabierta extends CI_Controller {

	/**
	* Controller action CREATE for controller respuestaabierta
	* autogenerated by CASE IGNITER
	*/
	public function create() {

		$this->load->model('encuesta_model');
		$data['body']['encuesta'] = $this->encuesta_model->get_all();

		$this->load->model('preguntaabierta_model');
		$data['body']['preguntaabierta'] = $this->preguntaabierta_model->get_all();

		enmarcar($this, 'respuestaabierta/create', $data);
	}

	
	
	/**
	* Controller action CREATE POST for controller respuestaabierta
	* autogenerated by CASE IGNITER
	*/
	public function create_post() {
		
		$this->load->model('respuestaabierta_model');

		$texto = ( isset( $_POST['texto']) ? $_POST['texto'] : null );
		$respondera = ( isset( $_POST['respondera']) ? $_POST['respondera'] : [] );
		$respuestasra = ( isset( $_POST['respuestasra']) ? $_POST['respuestasra'] : [] );

		try {
			$id = $this->respuestaabierta_model->create( $texto, $respondera, $respuestasra );
			$this->list_id($id);
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la respuestaabierta $texto";
			$this->load->view('respuestaabierta/create_message',$data);
		}	
	
	}
				
				
	
	/**
	* Controller action LIST for controller respuestaabierta
	* autogenerated by CASE IGNITER
	*/
	public function list() {
		$this->load->model('respuestaabierta_model');
		$filter = isset($_POST['filter'])?$_POST['filter']:'';
		$data['body']['respuestaabierta'] = ($filter == '' ? $this->respuestaabierta_model->get_all() : $this->respuestaabierta_model->get_filtered( $filter ) );
		enmarcar($this, 'respuestaabierta/list', $data);
	}

	/**
	* Controller private function LIST_ID for controller respuestaabierta
	* autogenerated by CASE IGNITER
	*/
	private function list_id($id) {
		$this->load->model('respuestaabierta_model');
		$data['body']['respuestaabierta'] = [ $this->respuestaabierta_model->get_by_id($id) ];
		enmarcar($this, 'respuestaabierta/list', $data);
	}


	
	/**
	* Controller action DELETE for controller respuestaabierta
	* autogenerated by CASE IGNITER
	*/
	public function delete() {
		$this -> load -> model ('respuestaabierta_model');
		try {
			$id = $_POST['id'];
			$this -> respuestaabierta_model -> delete( $id );
			redirect(base_url().'respuestaabierta/list');
		}
		catch (Exception $e ) {
			enmarcar($this, 'respuestaabierta/deleteERROR');
		}
	}	
	
	
	/**
	* Controller action UPDATE for controller respuestaabierta
	* autogenerated by CASE IGNITER
	*/
	public function update() {	
	
		$this->load->model('encuesta_model');
		$data['body']['encuesta'] = $this->encuesta_model->get_all();	
	
		$this->load->model('preguntaabierta_model');
		$data['body']['preguntaabierta'] = $this->preguntaabierta_model->get_all();

		$this -> load -> model ('respuestaabierta_model');
		$id = $_POST['id'];
		$data['body']['respuestaabierta'] = $this -> respuestaabierta_model -> get_by_id($id);
		
		enmarcar($this, 'respuestaabierta/update', $data);
	}	
	
	/**
	* Controller action UPDATE POST for controller respuestaabierta
	* autogenerated by CASE IGNITER
	*/
	public function update_post() {
	
		$this->load->model('respuestaabierta_model');
			
		$id = ( isset( $_POST['id']) ? $_POST['id'] : null );
		$texto = ( isset( $_POST['texto']) ? $_POST['texto'] : null );
		$respondera = ( isset( $_POST['respondera']) ? $_POST['respondera'] : [] );
		$respuestasra = ( isset( $_POST['respuestasra']) ? $_POST['respuestasra'] : [] );

		try {
			$this->respuestaabierta_model->update( $id, $texto, $respondera, $respuestasra );


			redirect( base_url() . 'respuestaabierta/list' );
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la respuestaabierta $texto";
			$this->load->view('respuestaabierta/create_message',$data);
		}	
	
	}
			
			}
?>