<?php
/**
* Controller code for respuestacerrada autogenerated by CASE IGNITER
*/
class respuestacerrada extends CI_Controller {

	/**
	* Controller action CREATE for controller respuestacerrada
	* autogenerated by CASE IGNITER
	*/
	public function create() {

		$this->load->model('encuesta_model');
		$data['body']['encuesta'] = $this->encuesta_model->get_all();

		$this->load->model('preguntacerrada_model');
		$data['body']['preguntacerrada'] = $this->preguntacerrada_model->get_all();

		enmarcar($this, 'respuestacerrada/create', $data);
	}

	
	
	/**
	* Controller action CREATE POST for controller respuestacerrada
	* autogenerated by CASE IGNITER
	*/
	public function create_post() {
		
		$this->load->model('respuestacerrada_model');

		$numero = ( isset( $_POST['numero']) ? $_POST['numero'] : null );
		$responderc = ( isset( $_POST['responderc']) ? $_POST['responderc'] : [] );
		$respuestasrc = ( isset( $_POST['respuestasrc']) ? $_POST['respuestasrc'] : [] );

		try {
			$id = $this->respuestacerrada_model->create( $numero, $responderc, $respuestasrc );
			$this->list_id($id);
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la respuestacerrada $numero";
			$this->load->view('respuestacerrada/create_message',$data);
		}	
	
	}
				
				
	
	/**
	* Controller action LIST for controller respuestacerrada
	* autogenerated by CASE IGNITER
	*/
	public function list() {
		$this->load->model('respuestacerrada_model');
		$filter = isset($_POST['filter'])?$_POST['filter']:'';
		$data['body']['respuestacerrada'] = ($filter == '' ? $this->respuestacerrada_model->get_all() : $this->respuestacerrada_model->get_filtered( $filter ) );
		enmarcar($this, 'respuestacerrada/list', $data);
	}

	/**
	* Controller private function LIST_ID for controller respuestacerrada
	* autogenerated by CASE IGNITER
	*/
	private function list_id($id) {
		$this->load->model('respuestacerrada_model');
		$data['body']['respuestacerrada'] = [ $this->respuestacerrada_model->get_by_id($id) ];
		enmarcar($this, 'respuestacerrada/list', $data);
	}


	
	/**
	* Controller action DELETE for controller respuestacerrada
	* autogenerated by CASE IGNITER
	*/
	public function delete() {
		$this -> load -> model ('respuestacerrada_model');
		try {
			$id = $_POST['id'];
			$this -> respuestacerrada_model -> delete( $id );
			redirect(base_url().'respuestacerrada/list');
		}
		catch (Exception $e ) {
			enmarcar($this, 'respuestacerrada/deleteERROR');
		}
	}	
	
	
	/**
	* Controller action UPDATE for controller respuestacerrada
	* autogenerated by CASE IGNITER
	*/
	public function update() {	
	
		$this->load->model('encuesta_model');
		$data['body']['encuesta'] = $this->encuesta_model->get_all();	
	
		$this->load->model('preguntacerrada_model');
		$data['body']['preguntacerrada'] = $this->preguntacerrada_model->get_all();

		$this -> load -> model ('respuestacerrada_model');
		$id = $_POST['id'];
		$data['body']['respuestacerrada'] = $this -> respuestacerrada_model -> get_by_id($id);
		
		enmarcar($this, 'respuestacerrada/update', $data);
	}	
	
	/**
	* Controller action UPDATE POST for controller respuestacerrada
	* autogenerated by CASE IGNITER
	*/
	public function update_post() {
	
		$this->load->model('respuestacerrada_model');
			
		$id = ( isset( $_POST['id']) ? $_POST['id'] : null );
		$numero = ( isset( $_POST['numero']) ? $_POST['numero'] : null );
		$responderc = ( isset( $_POST['responderc']) ? $_POST['responderc'] : [] );
		$respuestasrc = ( isset( $_POST['respuestasrc']) ? $_POST['respuestasrc'] : [] );

		try {
			$this->respuestacerrada_model->update( $id, $numero, $responderc, $respuestasrc );


			redirect( base_url() . 'respuestacerrada/list' );
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la respuestacerrada $numero";
			$this->load->view('respuestacerrada/create_message',$data);
		}	
	
	}
			
			}
?>