<?php
/**
* Controller code for titulacion autogenerated by CASE IGNITER
*/
class titulacion extends CI_Controller {

	/**
	* Controller action CREATE for controller titulacion
	* autogenerated by CASE IGNITER
	*/
	public function create() {

		$this->load->model('curso_model');
		$data['body']['curso'] = $this->curso_model->get_all();

		enmarcar($this, 'titulacion/create', $data);
	}

	
	
	/**
	* Controller action CREATE POST for controller titulacion
	* autogenerated by CASE IGNITER
	*/
	public function create_post() {
		
		$this->load->model('titulacion_model');

		$nombre = ( isset( $_POST['nombre']) ? $_POST['nombre'] : null );
		$tienetit = ( isset( $_POST['tienetit']) ? $_POST['tienetit'] : [] );

		try {
			$id = $this->titulacion_model->create( $nombre, $tienetit );
			$this->list_id($id);
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la titulacion $nombre";
			$this->load->view('titulacion/create_message',$data);
		}	
	
	}
				
				
	
	/**
	* Controller action LIST for controller titulacion
	* autogenerated by CASE IGNITER
	*/
	public function list() {
		$this->load->model('titulacion_model');
		$filter = isset($_POST['filter'])?$_POST['filter']:'';
		$data['body']['titulacion'] = ($filter == '' ? $this->titulacion_model->get_all() : $this->titulacion_model->get_filtered( $filter ) );
		enmarcar($this, 'titulacion/list', $data);
	}

	/**
	* Controller private function LIST_ID for controller titulacion
	* autogenerated by CASE IGNITER
	*/
	private function list_id($id) {
		$this->load->model('titulacion_model');
		$data['body']['titulacion'] = [ $this->titulacion_model->get_by_id($id) ];
		enmarcar($this, 'titulacion/list', $data);
	}


	
	/**
	* Controller action DELETE for controller titulacion
	* autogenerated by CASE IGNITER
	*/
	public function delete() {
		$this -> load -> model ('titulacion_model');
		try {
			$id = $_POST['id'];
			$this -> titulacion_model -> delete( $id );
			redirect(base_url().'titulacion/list');
		}
		catch (Exception $e ) {
			enmarcar($this, 'titulacion/deleteERROR');
		}
	}	
	
	
	/**
	* Controller action UPDATE for controller titulacion
	* autogenerated by CASE IGNITER
	*/
	public function update() {	
	
		$this->load->model('curso_model');
		$data['body']['curso'] = $this->curso_model->get_all();

		$this -> load -> model ('titulacion_model');
		$id = $_POST['id'];
		$data['body']['titulacion'] = $this -> titulacion_model -> get_by_id($id);
		
		enmarcar($this, 'titulacion/update', $data);
	}	
	
	/**
	* Controller action UPDATE POST for controller titulacion
	* autogenerated by CASE IGNITER
	*/
	public function update_post() {
	
		$this->load->model('titulacion_model');
			
		$id = ( isset( $_POST['id']) ? $_POST['id'] : null );
		$nombre = ( isset( $_POST['nombre']) ? $_POST['nombre'] : null );
		$tienetit = ( isset( $_POST['tienetit']) ? $_POST['tienetit'] : [] );

		try {
			$this->titulacion_model->update( $id, $nombre, $tienetit );


			redirect( base_url() . 'titulacion/list' );
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la titulacion $nombre";
			$this->load->view('titulacion/create_message',$data);
		}	
	
	}
			
			}
?>