<?php
/**
* Controller code for usuario autogenerated by CASE IGNITER
*/
class usuario extends CI_Controller {

	/**
	* Controller action CREATE for controller usuario
	* autogenerated by CASE IGNITER
	*/
	public function create() {

		$this->load->model('cursoacademico_model');
		$data['body']['cursoacademico'] = $this->cursoacademico_model->get_all();

		$this->load->model('departamento_model');
		$data['body']['departamento'] = $this->departamento_model->get_all();

		$this->load->model('encuesta_model');
		$data['body']['encuesta'] = $this->encuesta_model->get_all();

		$this->load->model('imparticion_model');
		$data['body']['imparticion'] = $this->imparticion_model->get_all();

		$this->load->model('grupo_model');
		$data['body']['grupo'] = $this->grupo_model->get_all();

		enmarcar($this, 'usuario/create', $data);
	}

	
	
	/**
	* Controller action CREATE POST for controller usuario
	* autogenerated by CASE IGNITER
	*/
	public function create_post() {
		
		$this->load->model('usuario_model');

		$nombre = ( isset( $_POST['nombre']) ? $_POST['nombre'] : null );
		$pwd = ( isset( $_POST['pwd']) ? $_POST['pwd'] : null );
		$rol = ( isset( $_POST['rol']) ? $_POST['rol'] : null );
		$trabaja = ( isset( $_POST['trabaja']) ? $_POST['trabaja'] : [] );
		$pertenece = ( isset( $_POST['pertenece']) ? $_POST['pertenece'] : [] );
		$realiza = ( isset( $_POST['realiza']) ? $_POST['realiza'] : [] );
		$desarrolla = ( isset( $_POST['desarrolla']) ? $_POST['desarrolla'] : [] );
		$grreferencia = ( isset( $_POST['grreferencia']) ? $_POST['grreferencia'] : [] );

		try {
			$id = $this->usuario_model->create( $nombre, $pwd, $rol, $trabaja, $pertenece, $realiza, $desarrolla, $grreferencia );
			$this->list_id($id);
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la usuario $nombre";
			$this->load->view('usuario/create_message',$data);
		}	
	
	}
				
				
	
	/**
	* Controller action LIST for controller usuario
	* autogenerated by CASE IGNITER
	*/
	public function list() {
		$this->load->model('usuario_model');
		$filter = isset($_POST['filter'])?$_POST['filter']:'';
		$data['body']['usuario'] = ($filter == '' ? $this->usuario_model->get_all() : $this->usuario_model->get_filtered( $filter ) );
		enmarcar($this, 'usuario/list', $data);
	}

	/**
	* Controller private function LIST_ID for controller usuario
	* autogenerated by CASE IGNITER
	*/
	private function list_id($id) {
		$this->load->model('usuario_model');
		$data['body']['usuario'] = [ $this->usuario_model->get_by_id($id) ];
		enmarcar($this, 'usuario/list', $data);
	}


	
	/**
	* Controller action DELETE for controller usuario
	* autogenerated by CASE IGNITER
	*/
	public function delete() {
		$this -> load -> model ('usuario_model');
		try {
			$id = $_POST['id'];
			$this -> usuario_model -> delete( $id );
			redirect(base_url().'usuario/list');
		}
		catch (Exception $e ) {
			enmarcar($this, 'usuario/deleteERROR');
		}
	}	
	
	
	/**
	* Controller action UPDATE for controller usuario
	* autogenerated by CASE IGNITER
	*/
	public function update() {	
	
		$this->load->model('cursoacademico_model');
		$data['body']['cursoacademico'] = $this->cursoacademico_model->get_all();	
	
		$this->load->model('departamento_model');
		$data['body']['departamento'] = $this->departamento_model->get_all();	
	
		$this->load->model('encuesta_model');
		$data['body']['encuesta'] = $this->encuesta_model->get_all();	
	
		$this->load->model('imparticion_model');
		$data['body']['imparticion'] = $this->imparticion_model->get_all();	
	
		$this->load->model('grupo_model');
		$data['body']['grupo'] = $this->grupo_model->get_all();

		$this -> load -> model ('usuario_model');
		$id = $_POST['id'];
		$data['body']['usuario'] = $this -> usuario_model -> get_by_id($id);
		
		enmarcar($this, 'usuario/update', $data);
	}	
	
	/**
	* Controller action UPDATE POST for controller usuario
	* autogenerated by CASE IGNITER
	*/
	public function update_post() {
	
		$this->load->model('usuario_model');
			
		$id = ( isset( $_POST['id']) ? $_POST['id'] : null );
		$nombre = ( isset( $_POST['nombre']) ? $_POST['nombre'] : null );
		$pwd = ( isset( $_POST['pwd']) ? $_POST['pwd'] : null );
		$rol = ( isset( $_POST['rol']) ? $_POST['rol'] : null );
		$trabaja = ( isset( $_POST['trabaja']) ? $_POST['trabaja'] : [] );
		$pertenece = ( isset( $_POST['pertenece']) ? $_POST['pertenece'] : [] );
		$realiza = ( isset( $_POST['realiza']) ? $_POST['realiza'] : [] );
		$desarrolla = ( isset( $_POST['desarrolla']) ? $_POST['desarrolla'] : [] );
		$grreferencia = ( isset( $_POST['grreferencia']) ? $_POST['grreferencia'] : [] );

		try {
			$this->usuario_model->update( $id, $nombre, $pwd, $rol, $trabaja, $pertenece, $realiza, $desarrolla, $grreferencia );


			redirect( base_url() . 'usuario/list' );
		}
		catch (Exception $e) {
			$data['status'] = 'error';
			$data['message'] = "Error al crear el/la usuario $nombre";
			$this->load->view('usuario/create_message',$data);
		}	
	
	}
			
			}
?>