<?php
/**
* Model code autogenerated by CASE IGNITER
*/
class aficion_model extends CI_Model {


	/**
	* create MODEL action autogenerated by CASE IGNITER
	*/
	public function create( $nombre ) {

	$bean = R::dispense( 'aficion' );


	// Regular attribute
	$bean -> nombre = $nombre;

	R::store($bean);

	return $bean->id;
}


	/**
	* update MODEL action autogenerated by CASE IGNITER
	*/
	public function update( $id, $nombre ) {

	$bean = R::load( 'aficion', $id );


	// Regular attribute
	$bean -> nombre = $nombre;

	R::store($bean);
}


	/**
	* get_all MODEL action autogenerated by CASE IGNITER
	*/
	public function get_all() {
		return R::findAll('aficion');
	}

	/**
	* get_filtered MODEL action autogenerated by CASE IGNITER
	*/
	public function get_filtered($filter) {

		$where_clause = [ ];

		$where_clause[] = 'nombre LIKE ?';
		$where_clause[] = '(SELECT nombre FROM persona WHERE persona.id = aficion.expertoen_id) LIKE ?';
		$where_clause[] = '(SELECT nombre FROM persona WHERE persona.id = aficion.inutilen_id) LIKE ?';
		$where_clause[] = '(SELECT count(*) FROM persona WHERE nombre LIKE ? AND persona.id IN (SELECT persona_id FROM odia WHERE aficion_id = aficion.id)) > 0';
		$where_clause[] = '(SELECT count(*) FROM persona WHERE nombre LIKE ? AND persona.id IN (SELECT persona_id FROM gusta WHERE aficion_id = aficion.id)) > 0';
		$f = "%$filter%";
		
		return R::findAll('aficion', implode(' OR ', $where_clause) , [ $f,$f,$f,$f,$f ] );
		
	}

	/**
	* delete MODEL action autogenerated by CASEIGNITER
	*/
	public function delete( $id ) {
		$bean = R::load('aficion', $id );
		R::trash( $bean );
	}
	
	/**
	* get_by_id MODEL action autogenerated by CASEIGNITER
	*/
	public function get_by_id( $id ) {
		return R::load('aficion', $id ) ;
	}
	
}
?>