<?php
/**
* Model code autogenerated by CASE IGNITER
*/
class aficion_model extends CI_Model {
public function create( $nombre, $tiene_pa ) {
	$bean = R::dispense( 'aficion' );

	$bean -> nombre = $nombre;
// TODO M2M
	R::store($bean);
}

	public function get_all() {
		return R::findAll('aficion');
	}
	public function get_filtered($filter) {
		return [];
	}

}
?>