<?php
/**
* Model code autogenerated by CASE IGNITER
*/
class asignatura_model extends CI_Model {


	/**
	* create MODEL action autogenerated by CASE IGNITER
	*/
	public function create( $nombre, $imparte, $refierea ) {

	$bean = R::dispense( 'asignatura' );


	// Regular attribute
	$bean -> setMeta("buildcommand.unique" , array(array('nombre')) );
	$bean -> nombre = $nombre;

	// "many to one" attribute
	if ( $imparte != null && $imparte != 0) {
		$bean -> imparte = R::load('departamento',$imparte);
	}
				
									
	// "one to many" attribute
	foreach ($refierea as $id) {
		$o2m = R::load('imparticion', $id);
		$bean -> alias('refierea') ->ownImparticionList[] = $o2m;
	}
				
				
	R::store($bean);

	return $bean->id;
}


	/**
	* update MODEL action autogenerated by CASE IGNITER
	*/
	public function update( $id, $nombre, $imparte, $refierea ) {

	$bean = R::load( 'asignatura', $id );


	// Regular attribute
	$bean -> nombre = $nombre;
	// "many to one" attribute
	if ( $imparte != null ) {
		$bean -> imparte = ( $imparte != 0 ? R::load('departamento',$imparte) : null );
		R::store($bean);
	}

				
	// "one to many" attribute (O2M)

	foreach ($bean->alias('refierea')->ownImparticionList as $refierea_bean ) {
		$key = array_search( $refierea_bean->refierea->id, $refierea );
		
		if ($key !== false) { // O2M we keep only the keys to add
			unset($refierea[$key]);
		}
		else { // O2M Element to be deleted
			R::store($bean);
			$refierea_bean -> refierea = null;
			R::store($refierea_bean);
		}
	}

	// O2M Elements to be added
	foreach ($refierea as $idf) {
		$o2m = R::load('imparticion', $idf);
		$o2m -> refierea = $bean;
		R::store($o2m);
	}


	R::store($bean);
}


	/**
	* get_all MODEL action autogenerated by CASE IGNITER
	*/
	public function get_all() {
		return R::findAll('asignatura');
	}

	/**
	* get_filtered MODEL action autogenerated by CASE IGNITER
	*/
	public function get_filtered($filter) {

		$where_clause[] = 'nombre LIKE ?';
		$where_clause[] = '(SELECT nombre FROM departamento WHERE departamento.id = asignatura.id) LIKE ?';
		$where_clause[] = '(SELECT nombre FROM imparticion WHERE imparticion.id = asignatura.id) LIKE ?';
		$f = "%$filter%";
		
		return R::findAll('ies', implode(' OR ', $where_clause) , [ $f,$f,$f ] );
		
	}

	/**
	* delete MODEL action autogenerated by CASEIGNITER
	*/
	public function delete( $id ) {
		$bean = R::load('asignatura', $id );
		R::trash( $bean );
	}
	
	/**
	* get_by_id MODEL action autogenerated by CASEIGNITER
	*/
	public function get_by_id( $id ) {
		return R::load('asignatura', $id ) ;
	}
	
}
?>