<?php
/**
* Model code autogenerated by CASE IGNITER
*/
class curso_model extends CI_Model {


	/**
	* create MODEL action autogenerated by CASE IGNITER
	*/
	public function create( $nivel, $pertenece, $tienetit ) {

	$bean = R::dispense( 'curso' );


	// Regular attribute
	$bean -> setMeta("buildcommand.unique" , array(array('nivel')) );
	$bean -> nivel = $nivel;
					
	// "one to many" attribute
	foreach ($pertenece as $id) {
		$o2m = R::load('grupo', $id);
		$bean -> alias('pertenece') ->ownGrupoList[] = $o2m;
	}
				
				
	// "many to one" attribute
	if ( $tienetit != null && $tienetit != 0) {
		$bean -> tienetit = R::load('titulacion',$tienetit);
	}
				
				
	R::store($bean);

	return $bean->id;
}


	/**
	* update MODEL action autogenerated by CASE IGNITER
	*/
	public function update( $id, $nivel, $pertenece, $tienetit ) {

	$bean = R::load( 'curso', $id );


	// Regular attribute
	$bean -> nivel = $nivel;
				
	// "one to many" attribute (O2M)

	foreach ($bean->alias('pertenece')->ownGrupoList as $pertenece_bean ) {
		$key = array_search( $pertenece_bean->pertenece->id, $pertenece );
		
		if ($key !== false) { // O2M we keep only the keys to add
			unset($pertenece[$key]);
		}
		else { // O2M Element to be deleted
			R::store($bean);
			$pertenece_bean -> pertenece = null;
			R::store($pertenece_bean);
		}
	}

	// O2M Elements to be added
	foreach ($pertenece as $idf) {
		$o2m = R::load('grupo', $idf);
		$o2m -> pertenece = $bean;
		R::store($o2m);
	}

	// "many to one" attribute
	if ( $tienetit != null ) {
		$bean -> tienetit = ( $tienetit != 0 ? R::load('titulacion',$tienetit) : null );
		R::store($bean);
	}


	R::store($bean);
}


	/**
	* get_all MODEL action autogenerated by CASE IGNITER
	*/
	public function get_all() {
		return R::findAll('curso');
	}

	/**
	* get_filtered MODEL action autogenerated by CASE IGNITER
	*/
	public function get_filtered($filter) {

		$where_clause[] = 'nivel LIKE ?';
		$where_clause[] = '(SELECT nombre FROM grupo WHERE grupo.id = curso.id) LIKE ?';
		$where_clause[] = '(SELECT nombre FROM titulacion WHERE titulacion.id = curso.id) LIKE ?';
		$f = "%$filter%";
		
		return R::findAll('ies', implode(' OR ', $where_clause) , [ $f,$f,$f ] );
		
	}

	/**
	* delete MODEL action autogenerated by CASEIGNITER
	*/
	public function delete( $id ) {
		$bean = R::load('curso', $id );
		R::trash( $bean );
	}
	
	/**
	* get_by_id MODEL action autogenerated by CASEIGNITER
	*/
	public function get_by_id( $id ) {
		return R::load('curso', $id ) ;
	}
	
}
?>