<?php
/**
* Model code autogenerated by CASE IGNITER
*/
class departamento_model extends CI_Model {


	/**
	* create MODEL action autogenerated by CASE IGNITER
	*/
	public function create( $nombre, $pertenece, $imparte, $gestiona ) {

	$bean = R::dispense( 'departamento' );


	// Regular attribute
	$bean -> setMeta("buildcommand.unique" , array(array('nombre')) );
	$bean -> nombre = $nombre;
					
	// "many to many" attribute
	foreach ($pertenece as $id) {
		$another_bean = R::load('usuario', $id);
		$m2m = R::dispense('pertenece');
		R::store($bean);
		$m2m -> departamento = $bean;
		$m2m -> usuario = $another_bean;
		R::store($m2m);
	}
				
									
	// "one to many" attribute
	foreach ($imparte as $id) {
		$o2m = R::load('asignatura', $id);
		$bean -> alias('imparte') ->ownAsignaturaList[] = $o2m;
	}
				
									
	// "many to many" attribute
	foreach ($gestiona as $id) {
		$another_bean = R::load('titulacion', $id);
		$m2m = R::dispense('gestiona');
		R::store($bean);
		$m2m -> departamento = $bean;
		$m2m -> titulacion = $another_bean;
		R::store($m2m);
	}
				
				
	R::store($bean);

	return $bean->id;
}


	/**
	* update MODEL action autogenerated by CASE IGNITER
	*/
	public function update( $id, $nombre, $pertenece, $imparte, $gestiona ) {

	$bean = R::load( 'departamento', $id );


	// Regular attribute
	$bean -> nombre = $nombre;
				
	// "many to many" attribute (M2M)
	
	foreach ($bean->ownPerteneceList as $pertenece_bean ) {
		$key = array_search( $pertenece_bean->usuario->id, $pertenece );
		
		if ($key !== false) { // M2M we keep only the keys to add
			unset($pertenece[$key]);
		}
		else { // M2M Element to be deleted
			R::store($bean);
			R::trash($pertenece_bean);
		}
	}

	// M2M Elements to be added
	foreach ($pertenece as $idf) {
		$another_bean = R::load('usuario', $idf);
		$m2m = R::dispense('pertenece');
		$m2m -> departamento = $bean;
		$m2m -> usuario = $another_bean;
		R::store($m2m);
	}

					
	// "one to many" attribute (O2M)

	foreach ($bean->alias('imparte')->ownAsignaturaList as $imparte_bean ) {
		$key = array_search( $imparte_bean->imparte->id, $imparte );
		
		if ($key !== false) { // O2M we keep only the keys to add
			unset($imparte[$key]);
		}
		else { // O2M Element to be deleted
			R::store($bean);
			$imparte_bean -> imparte = null;
			R::store($imparte_bean);
		}
	}

	// O2M Elements to be added
	foreach ($imparte as $idf) {
		$o2m = R::load('asignatura', $idf);
		$o2m -> imparte = $bean;
		R::store($o2m);
	}

				
	// "many to many" attribute (M2M)
	
	foreach ($bean->ownGestionaList as $gestiona_bean ) {
		$key = array_search( $gestiona_bean->titulacion->id, $gestiona );
		
		if ($key !== false) { // M2M we keep only the keys to add
			unset($gestiona[$key]);
		}
		else { // M2M Element to be deleted
			R::store($bean);
			R::trash($gestiona_bean);
		}
	}

	// M2M Elements to be added
	foreach ($gestiona as $idf) {
		$another_bean = R::load('titulacion', $idf);
		$m2m = R::dispense('gestiona');
		$m2m -> departamento = $bean;
		$m2m -> titulacion = $another_bean;
		R::store($m2m);
	}

	
	R::store($bean);
}


	/**
	* get_all MODEL action autogenerated by CASE IGNITER
	*/
	public function get_all() {
		return R::findAll('departamento');
	}

	/**
	* get_filtered MODEL action autogenerated by CASE IGNITER
	*/
	public function get_filtered($filter) {

		$where_clause[] = 'nombre LIKE ?';
		$where_clause[] = '(SELECT nombre FROM usuario WHERE usuario.id = departamento.id) LIKE ?';
		$where_clause[] = '(SELECT nombre FROM asignatura WHERE asignatura.id = departamento.id) LIKE ?';
		$where_clause[] = '(SELECT nombre FROM titulacion WHERE titulacion.id = departamento.id) LIKE ?';
		$f = "%$filter%";
		
		return R::findAll('ies', implode(' OR ', $where_clause) , [ $f,$f,$f,$f ] );
		
	}

	/**
	* delete MODEL action autogenerated by CASEIGNITER
	*/
	public function delete( $id ) {
		$bean = R::load('departamento', $id );
		R::trash( $bean );
	}
	
	/**
	* get_by_id MODEL action autogenerated by CASEIGNITER
	*/
	public function get_by_id( $id ) {
		return R::load('departamento', $id ) ;
	}
	
}
?>