<?php
/**
* Model code autogenerated by CASE IGNITER
*/
class encuesta_model extends CI_Model {


	/**
	* create MODEL action autogenerated by CASE IGNITER
	*/
	public function create( $fecha, $realiza, $realizada, $acercade, $responderc, $respondera ) {

	$bean = R::dispense( 'encuesta' );


	// Regular attribute
	$bean -> setMeta("buildcommand.unique" , array(array('fecha')) );
	$bean -> fecha = $fecha;

	// "many to one" attribute
	if ( $realiza != null && $realiza != 0) {
		$bean -> realiza = R::load('usuario',$realiza);
	}
				
				
	// "many to one" attribute
	if ( $realizada != null && $realizada != 0) {
		$bean -> realizada = R::load('imparticion',$realizada);
	}
				
				
	// "many to one" attribute
	if ( $acercade != null && $acercade != 0) {
		$bean -> acercade = R::load('plantillaencuesta',$acercade);
	}
				
				
	// "many to one" attribute
	if ( $responderc != null && $responderc != 0) {
		$bean -> responderc = R::load('respuestacerrada',$responderc);
	}
				
									
	// "one to many" attribute
	foreach ($respondera as $id) {
		$o2m = R::load('respuestaabierta', $id);
		$bean -> alias('respondera') ->ownRespuestaabiertaList[] = $o2m;
	}
				
				
	R::store($bean);

	return $bean->id;
}


	/**
	* update MODEL action autogenerated by CASE IGNITER
	*/
	public function update( $id, $fecha, $realiza, $realizada, $acercade, $responderc, $respondera ) {

	$bean = R::load( 'encuesta', $id );


	// Regular attribute
	$bean -> fecha = $fecha;
	// "many to one" attribute
	if ( $realiza != null ) {
		$bean -> realiza = ( $realiza != 0 ? R::load('usuario',$realiza) : null );
		R::store($bean);
	}

	// "many to one" attribute
	if ( $realizada != null ) {
		$bean -> realizada = ( $realizada != 0 ? R::load('imparticion',$realizada) : null );
		R::store($bean);
	}

	// "many to one" attribute
	if ( $acercade != null ) {
		$bean -> acercade = ( $acercade != 0 ? R::load('plantillaencuesta',$acercade) : null );
		R::store($bean);
	}

	// "many to one" attribute
	if ( $responderc != null ) {
		$bean -> responderc = ( $responderc != 0 ? R::load('respuestacerrada',$responderc) : null );
		R::store($bean);
	}

				
	// "one to many" attribute (O2M)

	foreach ($bean->alias('respondera')->ownRespuestaabiertaList as $respondera_bean ) {
		$key = array_search( $respondera_bean->respondera->id, $respondera );
		
		if ($key !== false) { // O2M we keep only the keys to add
			unset($respondera[$key]);
		}
		else { // O2M Element to be deleted
			R::store($bean);
			$respondera_bean -> respondera = null;
			R::store($respondera_bean);
		}
	}

	// O2M Elements to be added
	foreach ($respondera as $idf) {
		$o2m = R::load('respuestaabierta', $idf);
		$o2m -> respondera = $bean;
		R::store($o2m);
	}


	R::store($bean);
}


	/**
	* get_all MODEL action autogenerated by CASE IGNITER
	*/
	public function get_all() {
		return R::findAll('encuesta');
	}

	/**
	* get_filtered MODEL action autogenerated by CASE IGNITER
	*/
	public function get_filtered($filter) {

		$where_clause[] = 'fecha LIKE ?';
		$where_clause[] = '(SELECT nombre FROM usuario WHERE usuario.id = encuesta.id) LIKE ?';
		$where_clause[] = '(SELECT nombre FROM imparticion WHERE imparticion.id = encuesta.id) LIKE ?';
		$where_clause[] = '(SELECT nombre FROM plantillaencuesta WHERE plantillaencuesta.id = encuesta.id) LIKE ?';
		$where_clause[] = '(SELECT numero FROM respuestacerrada WHERE respuestacerrada.id = encuesta.id) LIKE ?';
		$where_clause[] = '(SELECT texto FROM respuestaabierta WHERE respuestaabierta.id = encuesta.id) LIKE ?';
		$f = "%$filter%";
		
		return R::findAll('ies', implode(' OR ', $where_clause) , [ $f,$f,$f,$f,$f,$f ] );
		
	}

	/**
	* delete MODEL action autogenerated by CASEIGNITER
	*/
	public function delete( $id ) {
		$bean = R::load('encuesta', $id );
		R::trash( $bean );
	}
	
	/**
	* get_by_id MODEL action autogenerated by CASEIGNITER
	*/
	public function get_by_id( $id ) {
		return R::load('encuesta', $id ) ;
	}
	
}
?>