<?php
/**
* Model code autogenerated by CASE IGNITER
*/
class gatito_model extends CI_Model {


	/**
	* create MODEL action autogenerated by CASE IGNITER
	*/
	public function create( $nombre, $foto, $loginname, $password, $roles ) {

	$bean = R::dispense( 'gatito' );
	$id_bean = R::store( $bean );


	// Regular attribute
	$bean -> nombre = $nombre;
					
	// Regular FILE attribute
	if ( $foto != NULL && $foto['error'] == UPLOAD_ERR_OK) {
		$name_and_ext = explode ( '.', $foto['name'] );
		$ext = $name_and_ext[sizeof ( $name_and_ext ) - 1 ];
		$file_name = 'gatito' . '-' . 'foto' . '-' . $id_bean . '.' .$ext ;
		copy ( $foto['tmp_name'], 'assets/upload/' .  $file_name );
		$bean -> foto = $file_name;	
	}

	// Regular attribute
	$bean -> loginname = $loginname;

	// Regular attribute
	$bean -> password = $password;
					
	// "many to many" attribute
	foreach ($roles as $id) {
		$another_bean = R::load('rol', $id);
		$m2m = R::dispense('roles');
		R::store($bean);
		$m2m -> gatito = $bean;
		$m2m -> rol = $another_bean;
		R::store($m2m);
	}
				
				
	R::store($bean);

	return $bean->id;
}


	/**
	* update MODEL action autogenerated by CASE IGNITER
	*/
	public function update( $id, $nombre, $foto, $loginname, $password ) {

	$bean = R::load( 'gatito', $id );

					
	// Regular attribute
	$bean -> nombre = $nombre;
						
	// Regular FILE attribute
	if ( $foto != NULL && $foto['error'] == UPLOAD_ERR_OK) {
		$name_and_ext = explode ( '.', $foto['name'] );
		$ext = $name_and_ext[sizeof ( $name_and_ext ) - 1 ];
		$file_name = 'gatito' . '-' . 'foto' . '-' . $id . '.' .$ext ;
		copy ( $foto['tmp_name'], 'assets/upload/' .  $file_name );
		if ($bean->foto != null && $bean->foto != '' ) {
			unlink( 'assets/upload/'.$bean->foto );
		}
		$bean -> foto = $file_name;
	}
						
	// Regular attribute
	$bean -> loginname = $loginname;
						
	// Regular attribute
	$bean -> password = $password;
	
	R::store($bean);
}


	/**
	* get_all MODEL action autogenerated by CASE IGNITER
	*/
	public function get_all() {
		return R::findAll('gatito');
	}

	/**
	* get_filtered MODEL action autogenerated by CASE IGNITER
	*/
	public function get_filtered($filter) {

		$where_clause = [ ];

		$where_clause[] = 'nombre LIKE ?';
		$where_clause[] = 'foto LIKE ?';
		$where_clause[] = 'loginname LIKE ?';
		$where_clause[] = '(SELECT count(*) FROM rol WHERE nombre LIKE ? AND rol.id IN (SELECT rol_id FROM roles WHERE gatito_id = gatito.id)) > 0';
		$f = "%$filter%";
		
		return R::findAll('gatito', implode(' OR ', $where_clause) , [ $f,$f,$f,$f ] );
		
	}

	/**
	* delete MODEL action autogenerated by CASEIGNITER
	*/
	public function delete( $id ) {
		$bean = R::load('gatito', $id );
		$file_path = 'assets/upload/'.($bean->foto);
		if (file_exists( $file_path )) {
			unlink( $file_path );
		} 

		R::trash( $bean );
	}	
	/**
	* get_by_id MODEL action autogenerated by CASEIGNITER
	*/
	public function get_by_id( $id ) {
		return R::load('gatito', $id ) ;
	}
		/**
	 * create MODEL action autogenerated by CASE IGNITER
	 */
	public function get_by_loginname( $loginname ) {
		return R::findOne( 'gatito', ' loginname = ? ', [ $loginname ] );
	}
			
}
?>