<?php
/**
* Model code autogenerated by CASE IGNITER
*/
class ies_model extends CI_Model {


	/**
	* create MODEL action autogenerated by CASE IGNITER
	*/
	public function create( $nombre, $ocurre ) {

	$bean = R::dispense( 'ies' );


	// Regular attribute
	$bean -> setMeta("buildcommand.unique" , array(array('nombre')) );
	$bean -> nombre = $nombre;
					
	// "one to many" attribute
	foreach ($ocurre as $id) {
		$o2m = R::load('cursoacademico', $id);
		$bean -> alias('ocurre') ->ownCursoacademicoList[] = $o2m;
	}
				
				
	R::store($bean);

	return $bean->id;
}


	/**
	* update MODEL action autogenerated by CASE IGNITER
	*/
	public function update( $id, $nombre, $ocurre ) {

	$bean = R::load( 'ies', $id );


	// Regular attribute
	$bean -> nombre = $nombre;
				
	// "one to many" attribute (O2M)

	foreach ($bean->alias('ocurre')->ownCursoacademicoList as $ocurre_bean ) {
		$key = array_search( $ocurre_bean->ocurre->id, $ocurre );
		
		if ($key !== false) { // O2M we keep only the keys to add
			unset($ocurre[$key]);
		}
		else { // O2M Element to be deleted
			R::store($bean);
			$ocurre_bean -> ocurre = null;
			R::store($ocurre_bean);
		}
	}

	// O2M Elements to be added
	foreach ($ocurre as $idf) {
		$o2m = R::load('cursoacademico', $idf);
		$o2m -> ocurre = $bean;
		R::store($o2m);
	}


	R::store($bean);
}


	/**
	* get_all MODEL action autogenerated by CASE IGNITER
	*/
	public function get_all() {
		return R::findAll('ies');
	}

	/**
	* get_filtered MODEL action autogenerated by CASE IGNITER
	*/
	public function get_filtered($filter) {

		$where_clause[] = 'nombre LIKE ?';
		$where_clause[] = '(SELECT anyoini FROM cursoacademico WHERE cursoacademico.id = ies.id) LIKE ?';
		$f = "%$filter%";
		
		return R::findAll('ies', implode(' OR ', $where_clause) , [ $f,$f ] );
		
	}

	/**
	* delete MODEL action autogenerated by CASEIGNITER
	*/
	public function delete( $id ) {
		$bean = R::load('ies', $id );
		R::trash( $bean );
	}
	
	/**
	* get_by_id MODEL action autogenerated by CASEIGNITER
	*/
	public function get_by_id( $id ) {
		return R::load('ies', $id ) ;
	}
	
}
?>