<?php
/**
* Model code autogenerated by CASE IGNITER
*/
class mascota_model extends CI_Model {
public function create( $nombre ) {
	$bean = R::dispense( 'mascota' );

	// Regular attribute
	$bean -> nombre = $nombre;

	R::store($bean);
}

	public function get_all() {
		return R::findAll('mascota');
	}
	public function get_filtered($filter) {
		return [];
	}

	/**
	* model delete action autogenerated by CASEIGNITER
	*/
	public function delete( $id ) {
		$bean = R::load('mascota', $id );
		R::trash( $bean );
	}
	
	/**
	* model get_by_id action autogenerated by CASEIGNITER
	*/
	public function get_by_id( $id ) {
		return R::load('mascota', $id );
	}
	
}
?>