<?php
/**
* Model code autogenerated by CASE IGNITER
*/
class mascota_model extends CI_Model {


	/**
	* create MODEL action autogenerated by CASE IGNITER
	*/
	public function create( $nombre ) {

	$bean = R::dispense( 'mascota' );
	$id_bean = R::store( $bean );


	// Regular attribute
	$bean -> nombre = $nombre;

	R::store($bean);

	return $bean->id;
}


	/**
	* update MODEL action autogenerated by CASE IGNITER
	*/
	public function update( $id, $nombre ) {

	$bean = R::load( 'mascota', $id );

					
	// Regular attribute
	$bean -> nombre = $nombre;
	
	R::store($bean);
}


	/**
	* get_all MODEL action autogenerated by CASE IGNITER
	*/
	public function get_all() {
		return R::findAll('mascota');
	}

	/**
	* get_filtered MODEL action autogenerated by CASE IGNITER
	*/
	public function get_filtered($filter) {

		$where_clause = [ ];

		$where_clause[] = 'nombre LIKE ?';
		$where_clause[] = '(SELECT nombre FROM persona WHERE persona.id = mascota.amo_id) LIKE ?';
		$f = "%$filter%";
		
		return R::findAll('mascota', implode(' OR ', $where_clause) , [ $f,$f ] );
		
	}

	/**
	* delete MODEL action autogenerated by CASEIGNITER
	*/
	public function delete( $id ) {
		$bean = R::load('mascota', $id );

		R::trash( $bean );
	}	
	/**
	* get_by_id MODEL action autogenerated by CASEIGNITER
	*/
	public function get_by_id( $id ) {
		return R::load('mascota', $id ) ;
	}
	
}
?>