<?php
/**
* Model code autogenerated by CASE IGNITER
*/
class pais_model extends CI_Model {
public function create( $nombre, $pais_nacimiento ) {
	$bean = R::dispense( 'pais' );

	$bean -> nombre = $nombre;
// TODO O2M
	R::store($bean);
}

	public function get_all() {
		return R::findAll('pais');
	}
	public function get_filtered($filter) {
		return [];
	}

}
?>