<?php
/**
* Model code autogenerated by CASE IGNITER
*/
class persona_model extends CI_Model {
public function create( $nombre, $fechaNacimiento, $peso, $amo, $paisNacimiento, $aficiones ) {
	$bean = R::dispense( 'persona' );

	// Regular attribute
	$bean -> nombre = $nombre;
	// Regular attribute
	$bean -> fechaNacimiento = $fechaNacimiento;
	// Regular attribute
	$bean -> peso = $peso;

	// "one to one" attribute
	$o2o = R::load('mascota',$amo);
	$bean -> amo = $o2o;
	R::store($bean);
	$o2o -> amo = $bean;
	R::store($o2o);

	// "many to one" attribute
	$bean -> paisNacimiento = R::load('pais',$paisNacimiento);
				
	// "many to many" attribute
	foreach ($aficiones as $id) {
		$another_bean = R::load('aficion', $id);
		$m2m = R::dispense('aficiones');
		R::store($bean);
		$m2m -> persona = $bean;
		$m2m -> aficion = $another_bean;
		R::store($m2m);
	}
	
	
	R::store($bean);
}

	public function get_all() {
		return R::findAll('persona');
	}
	public function get_filtered($filter) {
		return [];
	}

}
?>