<?php
/**
* Model code autogenerated by CASE IGNITER
*/
class preguntacerrada_model extends CI_Model {


	/**
	* create MODEL action autogenerated by CASE IGNITER
	*/
	public function create( $nombre, $enunciado, $enunciadofacil, $min, $max, $versacerrada, $componepc, $respuestasrc, $contienepc ) {

	$bean = R::dispense( 'preguntacerrada' );


	// Regular attribute
	$bean -> setMeta("buildcommand.unique" , array(array('nombre')) );
	$bean -> nombre = $nombre;

	// Regular attribute
	$bean -> setMeta("buildcommand.unique" , array(array('enunciado')) );
	$bean -> enunciado = $enunciado;

	// Regular attribute
	$bean -> setMeta("buildcommand.unique" , array(array('enunciadofacil')) );
	$bean -> enunciadofacil = $enunciadofacil;

	// Regular attribute
	$bean -> setMeta("buildcommand.unique" , array(array('min')) );
	$bean -> min = $min;

	// Regular attribute
	$bean -> setMeta("buildcommand.unique" , array(array('max')) );
	$bean -> max = $max;

	// "many to one" attribute
	if ( $versacerrada != null && $versacerrada != 0) {
		$bean -> versacerrada = R::load('asignatura',$versacerrada);
	}
				
				
	// "many to one" attribute
	if ( $componepc != null && $componepc != 0) {
		$bean -> componepc = R::load('plantillaencuesta',$componepc);
	}
				
				
	// "many to one" attribute
	if ( $respuestasrc != null && $respuestasrc != 0) {
		$bean -> respuestasrc = R::load('respuestacerrada',$respuestasrc);
	}
				
				
	// "many to one" attribute
	if ( $contienepc != null && $contienepc != 0) {
		$bean -> contienepc = R::load('categoria',$contienepc);
	}
				
				
	R::store($bean);

	return $bean->id;
}


	/**
	* update MODEL action autogenerated by CASE IGNITER
	*/
	public function update( $id, $nombre, $enunciado, $enunciadofacil, $min, $max, $versacerrada, $componepc, $respuestasrc, $contienepc ) {

	$bean = R::load( 'preguntacerrada', $id );


	// Regular attribute
	$bean -> nombre = $nombre;

	// Regular attribute
	$bean -> enunciado = $enunciado;

	// Regular attribute
	$bean -> enunciadofacil = $enunciadofacil;

	// Regular attribute
	$bean -> min = $min;

	// Regular attribute
	$bean -> max = $max;
	// "many to one" attribute
	if ( $versacerrada != null ) {
		$bean -> versacerrada = ( $versacerrada != 0 ? R::load('asignatura',$versacerrada) : null );
		R::store($bean);
	}

	// "many to one" attribute
	if ( $componepc != null ) {
		$bean -> componepc = ( $componepc != 0 ? R::load('plantillaencuesta',$componepc) : null );
		R::store($bean);
	}

	// "many to one" attribute
	if ( $respuestasrc != null ) {
		$bean -> respuestasrc = ( $respuestasrc != 0 ? R::load('respuestacerrada',$respuestasrc) : null );
		R::store($bean);
	}

	// "many to one" attribute
	if ( $contienepc != null ) {
		$bean -> contienepc = ( $contienepc != 0 ? R::load('categoria',$contienepc) : null );
		R::store($bean);
	}


	R::store($bean);
}


	/**
	* get_all MODEL action autogenerated by CASE IGNITER
	*/
	public function get_all() {
		return R::findAll('preguntacerrada');
	}

	/**
	* get_filtered MODEL action autogenerated by CASE IGNITER
	*/
	public function get_filtered($filter) {

		$where_clause[] = 'nombre LIKE ?';
		$where_clause[] = 'enunciado LIKE ?';
		$where_clause[] = 'enunciadofacil LIKE ?';
		$where_clause[] = 'min LIKE ?';
		$where_clause[] = 'max LIKE ?';
		$where_clause[] = '(SELECT nombre FROM asignatura WHERE asignatura.id = preguntacerrada.id) LIKE ?';
		$where_clause[] = '(SELECT nombre FROM plantillaencuesta WHERE plantillaencuesta.id = preguntacerrada.id) LIKE ?';
		$where_clause[] = '(SELECT numero FROM respuestacerrada WHERE respuestacerrada.id = preguntacerrada.id) LIKE ?';
		$where_clause[] = '(SELECT nombre FROM categoria WHERE categoria.id = preguntacerrada.id) LIKE ?';
		$f = "%$filter%";
		
		return R::findAll('ies', implode(' OR ', $where_clause) , [ $f,$f,$f,$f,$f,$f,$f,$f,$f ] );
		
	}

	/**
	* delete MODEL action autogenerated by CASEIGNITER
	*/
	public function delete( $id ) {
		$bean = R::load('preguntacerrada', $id );
		R::trash( $bean );
	}
	
	/**
	* get_by_id MODEL action autogenerated by CASEIGNITER
	*/
	public function get_by_id( $id ) {
		return R::load('preguntacerrada', $id ) ;
	}
	
}
?>