<?php
/**
* Model code autogenerated by CASE IGNITER
*/
class respuestaabierta_model extends CI_Model {


	/**
	* create MODEL action autogenerated by CASE IGNITER
	*/
	public function create( $texto, $respondera, $respuestasra ) {

	$bean = R::dispense( 'respuestaabierta' );


	// Regular attribute
	$bean -> setMeta("buildcommand.unique" , array(array('texto')) );
	$bean -> texto = $texto;

	// "many to one" attribute
	if ( $respondera != null && $respondera != 0) {
		$bean -> respondera = R::load('encuesta',$respondera);
	}
				
				
	// "many to one" attribute
	if ( $respuestasra != null && $respuestasra != 0) {
		$bean -> respuestasra = R::load('preguntaabierta',$respuestasra);
	}
				
				
	R::store($bean);

	return $bean->id;
}


	/**
	* update MODEL action autogenerated by CASE IGNITER
	*/
	public function update( $id, $texto, $respondera, $respuestasra ) {

	$bean = R::load( 'respuestaabierta', $id );


	// Regular attribute
	$bean -> texto = $texto;
	// "many to one" attribute
	if ( $respondera != null ) {
		$bean -> respondera = ( $respondera != 0 ? R::load('encuesta',$respondera) : null );
		R::store($bean);
	}

	// "many to one" attribute
	if ( $respuestasra != null ) {
		$bean -> respuestasra = ( $respuestasra != 0 ? R::load('preguntaabierta',$respuestasra) : null );
		R::store($bean);
	}


	R::store($bean);
}


	/**
	* get_all MODEL action autogenerated by CASE IGNITER
	*/
	public function get_all() {
		return R::findAll('respuestaabierta');
	}

	/**
	* get_filtered MODEL action autogenerated by CASE IGNITER
	*/
	public function get_filtered($filter) {

		$where_clause[] = 'texto LIKE ?';
		$where_clause[] = '(SELECT fecha FROM encuesta WHERE encuesta.id = respuestaabierta.id) LIKE ?';
		$where_clause[] = '(SELECT enunciado FROM preguntaabierta WHERE preguntaabierta.id = respuestaabierta.id) LIKE ?';
		$f = "%$filter%";
		
		return R::findAll('ies', implode(' OR ', $where_clause) , [ $f,$f,$f ] );
		
	}

	/**
	* delete MODEL action autogenerated by CASEIGNITER
	*/
	public function delete( $id ) {
		$bean = R::load('respuestaabierta', $id );
		R::trash( $bean );
	}
	
	/**
	* get_by_id MODEL action autogenerated by CASEIGNITER
	*/
	public function get_by_id( $id ) {
		return R::load('respuestaabierta', $id ) ;
	}
	
}
?>