<?php
/**
* Model code autogenerated by CASE IGNITER
*/
class respuestacerrada_model extends CI_Model {


	/**
	* create MODEL action autogenerated by CASE IGNITER
	*/
	public function create( $numero, $responderc, $respuestasrc ) {

	$bean = R::dispense( 'respuestacerrada' );


	// Regular attribute
	$bean -> setMeta("buildcommand.unique" , array(array('numero')) );
	$bean -> numero = $numero;

	// "many to one" attribute
	if ( $responderc != null && $responderc != 0) {
		$bean -> responderc = R::load('encuesta',$responderc);
	}
				
				
	// "many to one" attribute
	if ( $respuestasrc != null && $respuestasrc != 0) {
		$bean -> respuestasrc = R::load('preguntacerrada',$respuestasrc);
	}
				
				
	R::store($bean);

	return $bean->id;
}


	/**
	* update MODEL action autogenerated by CASE IGNITER
	*/
	public function update( $id, $numero, $responderc, $respuestasrc ) {

	$bean = R::load( 'respuestacerrada', $id );


	// Regular attribute
	$bean -> numero = $numero;
	// "many to one" attribute
	if ( $responderc != null ) {
		$bean -> responderc = ( $responderc != 0 ? R::load('encuesta',$responderc) : null );
		R::store($bean);
	}

	// "many to one" attribute
	if ( $respuestasrc != null ) {
		$bean -> respuestasrc = ( $respuestasrc != 0 ? R::load('preguntacerrada',$respuestasrc) : null );
		R::store($bean);
	}


	R::store($bean);
}


	/**
	* get_all MODEL action autogenerated by CASE IGNITER
	*/
	public function get_all() {
		return R::findAll('respuestacerrada');
	}

	/**
	* get_filtered MODEL action autogenerated by CASE IGNITER
	*/
	public function get_filtered($filter) {

		$where_clause[] = 'numero LIKE ?';
		$where_clause[] = '(SELECT fecha FROM encuesta WHERE encuesta.id = respuestacerrada.id) LIKE ?';
		$where_clause[] = '(SELECT nombre FROM preguntacerrada WHERE preguntacerrada.id = respuestacerrada.id) LIKE ?';
		$f = "%$filter%";
		
		return R::findAll('ies', implode(' OR ', $where_clause) , [ $f,$f,$f ] );
		
	}

	/**
	* delete MODEL action autogenerated by CASEIGNITER
	*/
	public function delete( $id ) {
		$bean = R::load('respuestacerrada', $id );
		R::trash( $bean );
	}
	
	/**
	* get_by_id MODEL action autogenerated by CASEIGNITER
	*/
	public function get_by_id( $id ) {
		return R::load('respuestacerrada', $id ) ;
	}
	
}
?>