<?php
/**
* Model code autogenerated by CASE IGNITER
*/
class rol_model extends CI_Model {


	/**
	* create MODEL action autogenerated by CASE IGNITER
	*/
	public function create( $nombre, $descripcion, $roles ) {

	$bean = R::dispense( 'rol' );
	$id_bean = R::store( $bean );


	// Regular attribute
	$bean -> nombre = $nombre;

	// Regular attribute
	$bean -> descripcion = $descripcion;
					
	// "many to many" attribute
	foreach ($roles as $id) {
		$another_bean = R::load('perrito', $id);
		$m2m = R::dispense('roles');
		R::store($bean);
		$m2m -> rol = $bean;
		$m2m -> perrito = $another_bean;
		R::store($m2m);
	}
				
				
	R::store($bean);

	return $bean->id;
}


	/**
	* update MODEL action autogenerated by CASE IGNITER
	*/
	public function update( $id, $nombre, $descripcion, $roles ) {

	$bean = R::load( 'rol', $id );

					
	// Regular attribute
	$bean -> nombre = $nombre;
						
	// Regular attribute
	$bean -> descripcion = $descripcion;
					
	// "many to many" attribute (M2M)
	
	foreach ($bean->ownRolesList as $roles_bean ) {
		$key = array_search( $roles_bean->perrito->id, $roles );
		
		if ($key !== false) { // M2M we keep only the keys to add
			unset($roles[$key]);
		}
		else { // M2M Element to be deleted
			R::store($bean);
			R::trash($roles_bean);
		}
	}

	// M2M Elements to be added
	foreach ($roles as $idf) {
		$another_bean = R::load('perrito', $idf);
		$m2m = R::dispense('roles');
		$m2m -> rol = $bean;
		$m2m -> perrito = $another_bean;
		R::store($m2m);
	}

	
	R::store($bean);
}


	/**
	* get_all MODEL action autogenerated by CASE IGNITER
	*/
	public function get_all() {
		return R::findAll('rol');
	}

	/**
	* get_filtered MODEL action autogenerated by CASE IGNITER
	*/
	public function get_filtered($filter) {

		$where_clause = [ ];

		$where_clause[] = 'nombre LIKE ?';
		$where_clause[] = 'descripcion LIKE ?';
		$where_clause[] = '(SELECT count(*) FROM perrito WHERE nombre LIKE ? AND perrito.id IN (SELECT perrito_id FROM roles WHERE rol_id = rol.id)) > 0';
		$f = "%$filter%";
		
		return R::findAll('rol', implode(' OR ', $where_clause) , [ $f,$f,$f ] );
		
	}

	/**
	* delete MODEL action autogenerated by CASEIGNITER
	*/
	public function delete( $id ) {
		$bean = R::load('rol', $id );

		R::trash( $bean );
	}	
	/**
	* get_by_id MODEL action autogenerated by CASEIGNITER
	*/
	public function get_by_id( $id ) {
		return R::load('rol', $id ) ;
	}
	
}
?>