<?php
/**
* Model code autogenerated by CASE IGNITER
*/
class titulacion_model extends CI_Model {


	/**
	* create MODEL action autogenerated by CASE IGNITER
	*/
	public function create( $nombre, $tienetit ) {

	$bean = R::dispense( 'titulacion' );


	// Regular attribute
	$bean -> setMeta("buildcommand.unique" , array(array('nombre')) );
	$bean -> nombre = $nombre;
					
	// "one to many" attribute
	foreach ($tienetit as $id) {
		$o2m = R::load('curso', $id);
		$bean -> alias('tienetit') ->ownCursoList[] = $o2m;
	}
				
				
	R::store($bean);

	return $bean->id;
}


	/**
	* update MODEL action autogenerated by CASE IGNITER
	*/
	public function update( $id, $nombre, $tienetit ) {

	$bean = R::load( 'titulacion', $id );


	// Regular attribute
	$bean -> nombre = $nombre;
				
	// "one to many" attribute (O2M)

	foreach ($bean->alias('tienetit')->ownCursoList as $tienetit_bean ) {
		$key = array_search( $tienetit_bean->tienetit->id, $tienetit );
		
		if ($key !== false) { // O2M we keep only the keys to add
			unset($tienetit[$key]);
		}
		else { // O2M Element to be deleted
			R::store($bean);
			$tienetit_bean -> tienetit = null;
			R::store($tienetit_bean);
		}
	}

	// O2M Elements to be added
	foreach ($tienetit as $idf) {
		$o2m = R::load('curso', $idf);
		$o2m -> tienetit = $bean;
		R::store($o2m);
	}


	R::store($bean);
}


	/**
	* get_all MODEL action autogenerated by CASE IGNITER
	*/
	public function get_all() {
		return R::findAll('titulacion');
	}

	/**
	* get_filtered MODEL action autogenerated by CASE IGNITER
	*/
	public function get_filtered($filter) {

		$where_clause[] = 'nombre LIKE ?';
		$where_clause[] = '(SELECT nivel FROM curso WHERE curso.id = titulacion.id) LIKE ?';
		$f = "%$filter%";
		
		return R::findAll('ies', implode(' OR ', $where_clause) , [ $f,$f ] );
		
	}

	/**
	* delete MODEL action autogenerated by CASEIGNITER
	*/
	public function delete( $id ) {
		$bean = R::load('titulacion', $id );
		R::trash( $bean );
	}
	
	/**
	* get_by_id MODEL action autogenerated by CASEIGNITER
	*/
	public function get_by_id( $id ) {
		return R::load('titulacion', $id ) ;
	}
	
}
?>